import json
S = "/tmp/claude-0/-home-user/5e9c60cb-7f47-59f3-839d-3523d9acb3c2/scratchpad"
d = json.load(open(S + "/verdicts.json"))
L, A = d["lines"], d["assigned"]
VERD = {"D": "DELETE", "M": "MERGE", "R": "REWRITE", "K": "KEEP"}
def files(g): return sorted([f for f, x in A.items() if x == g], key=lambda f: -L[f])
def fmt(fs): return ", ".join(f"`{f.replace('level0/','l0/').replace('contract/','c/')}` ({L[f]})" for f in fs)
def tot(fs): return sum(L[f] for f in fs)

EV = {
"D1": ("The JS bridge server and its door handlers (`src/bridge/*`)",
"`migration.phase5switch` (go-cage-switches-over: *\"Done when the bridge server leaves the tree\"*). None of `src/bridge/{agent,answer,answer-read,apply,ask,bash,binding,bless,cloud-ask,code,grace,guidance,index-tools,plan,prose,review,search,stop,tools,vale-rows,wait,write}.js` is imported by any production entry; the plugin entry `.claude/skills/level0/hooks/pull-tool.js` reaches only `hooks/{level0,cage,clear,shape,start,transcript}.js` + `lib/{config,folders,guidance,index,index-tools,layer,log,pull,tools,vehicle}.js` (17 modules) and posts every event to the Go hooks door. The `bridge/handover`, `bridge/findings`, `bridge/config` exports these tests drive are the dead ones (only `handover#RESUME` and two `findings` exports stay live, for probe-dry and prepush). Go owns each behavior: `src/modules/hooks/{answers,brief,cage,command,commits,describe,fold,holds,prompt,questions,review,search,spawn,stops,writes}_test.go`, `src/modules/hooks/{write,stop,brief,command}/*_test.go`, `src/modules/{plans,waits,search,drafts}/*_test.go`. Twin evidence: `command-cases`, `commit-guards-cases`, `brief-cases` and `c/write-door-cases` read the same `test/replay/cage/*-cases.json` files that `src/modules/hooks/{command,commits,brief,writes}_test.go` read."),
"D2": ("Level-zero lib rule modules, prose checks, schema checker, dead doors",
"`migration.phase5switch` (cage rules) and `migration.phase10` (node-leaves-the-boxes: *\"The Go prose checks become the only copy\"*). Modules never loaded from any entry: `lib/{answer,apply,bash,bash-test,candidate-check,code,commit-reads,controls,git-writes,magic,names,paragraph,paragraph-rules,plugin-check,projection,pulled,review,rulefile,schema-body,schema-mint,schema-table,servers,shell-values,size,stop,tokens,tree,undo,verb-line,vocabulary,voice,warnings}.js`, `src/engine/status.js`, `src/scripts/graph.js`, `src/extension/lib/grid.js`, and the doors `src/doors/{awake,biome,vale,wire}.js` (no non-test importer; `wire.js` is only a test server for http/editor-index). Partly-loaded modules are dead in exactly the exports these tests drive: `lib/guidance.js` 2/23 exports live (`REPLY_PROBE`, `HEARD`), `lib/schema.js` 4/55 live (extension's `readNote`/`sectionAt` only), `lib/ticket.js` 1/15, `lib/log.js` `reasonIn`/`wroteSince` dead, `lib/config.js` `underBuiltIns`/`keyOf` dead. Go owners: `src/modules/hooks/command/*_test.go` (bash, tokens, trunk, todo, private, tested, voice), `src/modules/hooks/stop/stop_test.go`, `src/projection/projection_test.go` (paragraph/projection/vocabulary), `src/voice/voice_test.go` + `src/prose/*_test.go` (voice/verbs/names), `src/modules/check/{schema,sweep,mint,reroute,textfaults,note}_test.go` (schema*, size, magic), `src/modules/edits/*_test.go` (apply/undo), `src/modules/tickets/graph_test.go` (graph), `src/modules/lsp/*_test.go` (biome/vale one-reading), `src/quack/setup_verb_test.go` (servers pin)."),
"D3": ("JS verb programs: ticket, pull, work (non-take), box and read verbs",
"`migration.phase4switch` (quack-verbs-switch-over: *\"cli.js leaves the tree\"*) and `migration.phase11` (the-verbs-run-in-go: *\"programOf hands no verb to node, and src/scripts/verbs/ leaves the tree\"*). `RUNME.sh` execs `se-index verb src/scripts <verb>`; `src/scripts/verbs/` no longer exists so the node fallback never fires; `src/quack/verbs.go` routes every registered verb to Go, and the Go `node` module (`nodeAccept` in `src/quack/twins.go`) also answers with Go twins only. Static symbol trace: `scripts/pull.js` 0/13 exports live, `scripts/ticket.js` 1/12, `work.js#pulling` dead, `pull-hand.js` 6/31, `pull-writes.js` 3/23, `pull-chapter.js` 2/21, `pull-escalate.js` 0/4, `guidance-hand.js` 2/26 (`heldTests`/`everyHold` via precommit only); `serve,browser,trust,battery,cli-read,cli-check,cli-go,tui-build,quack-topic,process,work-answer,work-fix,work-list,work-merge,work-review,work-test,work-unblock,ticket-*` are never loaded. Go ports name these files: `src/pull/route_test.go` (ticket-route/drift/verb), `src/pull/pull_test.go` (pull, level1, pull-gate), `src/quack/ticket_{new,note,todo,set,urgent,place,open,bless}_test.go` (ticket-*, ask-lint, bless-desk, pull-bless), `src/branches/port_{a..f}_*_test.go` (work-done/fix/open/rows/list/merge-cloud/cloud-marker/answer, review, unblock, test-verb, pull-escalate), `src/quack/{battery,serve_verb,browser,tui_verb,verb_lint,brand}_test.go`, `src/modules/queue/*_test.go` (queue, queue-cloud, outline)."),
"D4": ("Migration scaffolding: twin goldens, parity checks, leave-guards",
"Shadow/twin tooling for phases 3, 4, 5, 8 and 11 that all read true. Golden writers `config-golden.js`, `guidance-golden.js`, `log-golden.js`, `queue-golden.js`, `drawn-twin.js` and `check-twins.js` run dead JS (`scripts/{config,guidance,log}-golden.js`, `scripts/graph.js`, `scripts/check-twins.js`, none loaded) to feed Go parity tests (`src/quack/{config,guidance,log,check_twins}_test.go`, `src/modules/queue/golden_test.go`, `src/modules/tickets/drawn_test.go`); the goldens are now frozen Go fixtures. `c/lint-twins` compares the Go lint with dead `cli-read.js`; `c/runme-road` and `c/topic-keys` assert phase-switch modes; `c/{bridge-server-leaves,cli-leaves,log-read-leaves,no-old-server,no-road-names-server,node-road,twins-left,dead-entries,cli-check-doors,cli-read}` assert that a migrated file left or reads the source of a dead file. Git history holds those facts; `src/quack/{no_program,programs,verbs}_test.go` already pin the Go side."),
"M1": ("The JS `work take` path, alive only through Copilot dispatch, duplicated by Go `branch take`",
"One import keeps ~5.3k lines of `src/scripts/{work,work-*,pull-*,ticket}*.js` loaded: `.claude/skills/level0/lib/copilot-dispatch.js` imports `work` from `src/scripts/work.js` and calls `work(root, [\"take\"])` (run by a person as `node src/scripts/copilot.js dispatch`, spec/design_output/copilot.md). Every other `WORK_VERBS` entry is unreachable (`pull-route.js` only reads `Object.keys(WORK_VERBS)`). These tests drive `take`/`sync`/`standing` or helpers on that path, and each already has a Go port that names it: `src/branches/port_a_take_test.go`, `port_a_marks_test.go`, `port_b_take_test.go`, `port_b_group_test.go`, `port_b_waits_test.go` (work-chain, work-gate), `port_c_held_test.go`, `port_d_{switch,orphan,desk,sync,stands}_test.go`, `port_a_fixtures_test.go`/`port_b_fixtures_test.go` (work-doors.js), `src/pull/pull_when_test.go`, `src/modules/tickets/red_test.go` (pull-kept). Merge = point copilot dispatch at `./RUNME.sh branch take` (Go), then delete these and the take-chain sources together."),
"M2": ("Shipped-data checks read through dead JS readers",
"Each case asserts something about files the tree ships (schemas, routes, guidance notes, the tree layout, vocabulary), which is real behavior, but reads them through dead JS: `lib/schema.js` checker (51/55 exports dead), `lib/schema-mint.js`/`schema-route.js`, `lib/tree.js` (never loaded; Go `src/modules/check/tree.go` owns the tree rules), `lib/stop.js` + `bridge/stop.js`, `lib/guidance.js#actionables`, `lib/vocabulary.js`. Move the still-wanted assertions into the Go readers' tests (`src/modules/check/{schema,sweep,features}_test.go`, `src/pull/process_test.go`, `src/modules/hooks/stop/stop_test.go`, `src/modules/guidance`, `src/projection/projection_test.go`, `src/prose/words`), which already read `spec/` in places (`src/modules/check/features_test.go`, `src/quack/verb_mint_test.go`), then delete."),
"M3": ("JS tests duplicating a Go test of the same table",
"`c/cli-verbs`, `c/verb-programs` (and their helper `c/commands.js` for these two) parse `src/modules/verbs/tree.go` as text from JS to check the Go verb table; `src/quack/{verbs,programs,no_program}_test.go` test the same table through Go. `copilot-setup` tests `lib/copilot-setup.js` registrations that `src/quack/copilotsetup_test.go` also tests (`copilotRegistrations` in `src/quack/copilotsetup.go`); two live implementations, one should go (the workflow `.github/workflows/copilot-setup-steps.yml` still calls the JS one)."),
"M4": ("Extension and start-road tests re-driving behaviors another file already drives",
"Since `migration.phase8switch` every sidebar/lens read and write goes through the index, and every test here uses the same fake (`v1-index.js`). `sidebar-writes` (config/opened, config/override, each button posts its action) restates `sidebar.test` cases \"a set message holds an override\", \"a window opening under a new id drops the overrides\", \"a run message opens the run\"; its source-grep case restates `c/sidebar-reads-no-file`. `sidebar-v1` (\"draws the config tree … off a fake index\", \"a watch event draws the sidebar again\") restates `sidebar.test` \"the sidebar draws the widgets\" / \"the view opening draws the page once, and the watcher draws it again\". `lens-v1` and `lens-actions` restate `lens.test` button/save cases over the same fake, plus source greps (`names no door.read`, `names no verb program folder`). `start-constants` (27) asserts two constants `start.test` and `hooks.test` already read. Fold each into its parent file."),
"R1": ("Live modules whose tests also drive dead exports",
"The module is loaded by an entry, but some cases drive exports nothing loads. Drop those cases and keep the rest: `folders` (`inRetro`,`runs` dead), `trunk` (`touchesGit`,`landsOnTrunk`,`versionRefs` dead; `refusedVersion` live via prepush; Go `hooks/command/trunk_test.go`), `layer` (only `deeply` live), `log` (`archiveOf`,`rowsOf`,`asRow`,`tallied`,`logSpec`,… dead), `tools` (`rebuilt`,`versionOf`,`installedTools`,`engine/tools#survey` dead), `paths` (only `runsHere` live), `private` (`refusedPrivate`,`carriedFrom`,`sharedIdentifiers`,… dead; Go `hooks/command/private_test.go`), `index` (`asked`,`said` dead), `cloud-desk` (`onDesk`, `pull-push#pushed` dead), `landed` (`landed`,`unlandedRows` dead; `landedAlone` live), `guidance-hand` (only `heldTests`/`everyHold` live via precommit; ~300 of 368 lines drive `resolved`/`tagsOf`/`heldReads`/`pulling`), `vehicle` (`attaches`,`travels`, `scripts/vehicle#attach/detach/produce` dead; Go `src/vehicle/*_test.go`), `probe-cold` (`probeCold`,`coldIn`,`stepsOf`,`readsCold`,`carriesLogin` dead; Go `src/quack/probe_cold_test.go`), `hooks` (3 `bridge/write#wholeAfter` cases dead, 7 boot cases live), `cage` (\"the JavaScript layer matches the case table\" is a twin of `layer-cases.json` through dead `bridge/guidance.js`), `outside-hand` (guidance and work-verb cases dead), `stand` (`freeNow`,`standingOf` dead; `staleClaim`/`freeIn` live via prepush), `save-fills` (drives dead `scripts/ticket.js` as the save), `c/install` (`servers#valeLsAsset`, `tools#rebuilt` dead), `c/vehicle` (`produce` dead), `c/tree-extension` (`grid#faultsIn`, `config#underBuiltIns` dead)."),
"R2": ("Live behavior tested through a dead helper (walks around the door)",
"`v1-index.js` is the fake index for 12 extension tests, but it draws tickets through `drawn-twin.js` → dead `src/scripts/graph.js` instead of the Go projection the real index serves; feed it the Go golden (`src/modules/tickets/testdata`) and drop `drawn-twin.js`. `drawing-edit` and `c/drawing-page` build their graphs with dead `graph.js`/`ticket-route.js`, and `c/drawing-page` launches the browser through dead `scripts/browser.js` (see `c/dead-entries`). `c/ruled.js` (helper of `c/{paragraph,shape,vale-fix,outside-in-doors,vale,process,schema}`) parses Vale output with dead `lib/vale.js#fromJson/faultIn/unreasoned`; the rule assertions are worth keeping (they run the shipped `spec/config/styles` through the real Vale) but should not depend on a dead parser. `c/vale` additionally carries the contract case for the dead JS Vale door `src/doors/vale.js`; drop that case."),
"R3": ("Over-covering parent file",
"`sidebar.test.js` (527 lines, 29 cases) keeps case names from the file-reading road (\"the widget follows the file, because a redraw reads the file again\") that `phase8switch` replaced with index reads; rewrite those against the index fake when folding in M4."),
}

order = ["D1","D2","D3","D4","M1","M2","M3","M4","R1","R2","R3"]
out = []
w = out.append
tv = {}
for g in ["D1","D2","D3","D4","M1","M2","M3","M4","R1","R2","R3","K"]:
    v = VERD[g[0]]; fs = files(g)
    tv.setdefault(v, [0, 0]); tv[v][0] += len(fs); tv[v][1] += tot(fs)
total_f = len(L); total_l = sum(L.values())
w("# JavaScript test audit: test/level0 and test/contract\n")
w("Read-only audit of `/home/user/quackitect` on main, 2026-10-06. Scope: 275 files in `test/level0` (44,256 lines) and 78 in `test/contract` (7,955 lines), 353 files and 52,211 lines in all, counting helpers.\n")
w("## Totals\n")
w("| Verdict | Files | Lines | Share of lines |\n|---|---:|---:|---:|")
for v in ["DELETE","MERGE","REWRITE","KEEP"]:
    w(f"| {v} | {tv[v][0]} | {tv[v][1]:,} | {100*tv[v][1]/total_l:.0f}% |")
w(f"| **Total** | **{total_f}** | **{total_l:,}** | |\n")
w("After DELETE and MERGE, about 17.7k test lines remain (KEEP + REWRITE, before trimming), against about 19.2k lines of JS that some production path still loads. Today the ratio is 52.2k test lines to 33.9k JS lines in all (1.54x), and most of that JS no longer runs.\n")
w("## How \"no production path runs it\" was established\n")
w("""1. **Entry points, from the configs that start JS.** These are `.claude/skills/level0/hooks/hooks.json` → `pull-tool.js` (`register`); `.claude/settings.json` SessionStart → `src/scripts/boot.js`; `.githooks/pre-commit` → `src/scripts/precommit.js`; `.githooks/pre-push` → `src/scripts/prepush.js` (install.sh sets `core.hooksPath`); `.github/hooks/level0.json` and `copilot-setup-steps.yml` → `src/scripts/copilot.js` (modes `hook`, `setup`, and the person-run `dispatch`); and `src/quack/probe_verb.go` → `src/scripts/probe-dry.js`. `src/quack/check.go` loads `src/scripts/battery-reporter.js` as the `node --test` reporter. The VS Code extension `src/extension/extension.js` dynamically imports `src/bridge/vehicle.js` and `src/doors/{proc,disk,clock}.js`, and its webview loads `webview/clicks.js` and the `webview/route/*.js` bundle. The stub bridgehead imports nothing.
2. **RUNME.sh starts no JS verb.** It execs `.se/.runtime/bin/se-index verb src/scripts <verb>`. Its fallback, `node src/scripts/verbs/$1.js`, finds nothing because `src/scripts/verbs/` is gone. `package.json` has no scripts. In Go, `roadOf` in `src/quack/verbs.go` sends every registered verb to Go, and the `node` IO module (`nodeAccept`, `src/quack/twins.go`) answers through Go twins and refuses anything else. No other non-test Go file names a JS file to run: the only hits for a `.js` string are `probe-dry.js`, `battery-reporter.js` and the `node src/scripts/copilot.js` runner that the Copilot setup writes into the hook registrations.
3. **Symbol-level reachability.** A TypeScript-AST pass over all 598 JS files walked from the entries' exported or top-level code through named, namespace and dynamic imports and re-exports. Inside a module it followed the top-level declarations each function references. It found 123 of 231 source modules loaded and 1,522 symbols live. Each test's imported subjects (taken directly or through its helper files, with fakes excluded) were checked against that set. Two dispatcher overrides were applied: Copilot `dispatch` reaches `work()` only with `["take"]`, and `pull-route.js` reads only `Object.keys(WORK_VERBS)`. Without the overrides every JS pull and ticket function would count as live, through a key listing.
4. **Go duplicates.** Go test files that say they port a JS test (`grep 'test/level0/' src/**/*_test.go`, 55 files) and Go tests that read the same `test/replay/cage/*-cases.json` as a JS test.
5. **Phase keys.** These come from `src/modules/migration/migration.go` and `spec/tickets/*`: phase3 read topics, phase4 quack verbs (\"cli.js leaves\"), phase5 Go cage (\"bridge server leaves the tree\"), phase6 TUI, phase7 LSP door, phase8 sidebar on the index, phase9 module processes, phase10 \"Go prose checks become the only copy\", and phase11 \"programOf hands no verb to node\".
""")
w("## Verdicts by group\n")
for g in order:
    fs = files(g); title, ev = EV[g]
    w(f"### {VERD[g[0]]} — {g}: {title}  ({len(fs)} files, {tot(fs):,} lines)\n")
    w(f"**Evidence.** {ev}\n")
    w(f"**Files.** {fmt(fs)}\n")
ks = files("K")
w(f"### KEEP ({len(ks)} files, {tot(ks):,} lines)\n")
w("""**Evidence.** Each of these drives code a production entry loads, through its interface and over fakes. The exceptions are the door contract tests, which each run one real door once: `c/{disk,proc,git,clock,log,http,front,index,session,editor-files,editor-index,desk-start}`. `c/real-git` enforces the one-real-door rule. The groups are:
- **Bridgehead.** `pull-tool.js`, `level0.js`, `cage.js`, `start.js`, `clear.js`, `shape.js`, `transcript.js` and the stub `bridgehead.js`.
- **Person-side git hooks.** `precommit.js` and `prepush.js` with `private`, `markers`, `tested`, `todo` and `runs`.
- **Copilot.** `copilot.js`, `copilot-door.js`, `copilot-dispatch.js`, `mutations.js`, `styles.js` and the `session` door.
- **Probes.** `probe-dry.js` and `probe-clear.js`.
- **Extension and webview.** `extension.js`, `sidebar.js`, `editor-*.js`, `lib/*`, `webview/clicks.js` and `webview/route/*`.
- **Engine and config.** `engine/group.js`, which Copilot dispatch and prepush use, `engine/front-merge.js`, `lib/config.js` and `doors/front.js`.
- **Repo-shape checks still in force.** Workflows, skills, `go.mod`, `go-stamp.sh`, the shipped drawing, and the extension's index-only rule.

Small dead imports inside KEEP files are noted but not counted against them: `wire.js` as a test server in `c/http` and `c/editor-index`, and `graph.js` reached through the `v1-index.js` helper, fixed under R2.
""")
w(f"**Files.** {fmt(ks)}\n")

dl = sorted([f for f, x in A.items() if x.startswith("D")], key=lambda f: -L[f])[:10]
w("## Top 10 deletions\n")
w("| # | File | Lines | Group | Why |\n|---|---|---:|---|---|")
why = {}
for f in dl:
    why[f] = A[f]
reasons = {
 "level0/bash.test.js": "lib/bash, commit-reads, verb-line, git-writes and scripted rules are never loaded; Go `src/modules/hooks/command/*_test.go`",
 "level0/projection.test.js": "lib/projection.js is never loaded (phase10); Go `src/projection/projection_test.go`",
 "level0/pull-steps.test.js": "drives `pull`, `pulling`, `withPersonStep` and `childrenSay`, all dead (phase11); Go `src/pull/pull_test.go`",
 "level0/pull.test.js": "`work.js#pulling` and `serve.js#startOf` are dead; Go `src/pull/pull_test.go` says it was ported from this file",
 "level0/work-answer.test.js": "work-answer.js is never loaded; Go `src/modules/work/rows_test.go`, `src/branches/port_*`",
 "level0/unblock.test.js": "work-unblock.js is never loaded; Go `src/branches/port_f_unblock_test.go` (ported from this file)",
 "level0/review.test.js": "lib/review.js and work-review.js are never loaded; Go `src/branches/port_f_review_test.go` and `src/modules/hooks/review_test.go`",
 "level0/work-done.test.js": "the `done` subverb never runs from JS; Go `src/branches/port_c_done_test.go` (ported from this file)",
 "level0/stop-door.test.js": "bridge/stop.js and bridge/answer.js are never loaded (phase5switch); Go `src/modules/hooks/stops_test.go` and `stop/stop_test.go`",
 "level0/pull-leaves.test.js": "`pulling`, `verdictIn`, `commandsRun` and work-test are dead; Go `src/pull`, `src/branches/port_f_testverb_test.go`",
 "level0/stop.test.js": "lib/stop.js is never loaded; Go `src/modules/hooks/stop/stop_test.go`",
 "level0/schema-slots.test.js": "the lib/schema checker is dead (51 of 55 exports); Go `src/modules/check/*_test.go`",
}
for i, f in enumerate(dl, 1):
    w(f"| {i} | `test/{f}` | {L[f]} | {A[f]} | {reasons.get(f, '')} |")
w("")
w("## Over-coverage still standing after the cut (a watch list, not counted above)\n")
w("""- **Bridgehead.** `hooks/*.js` is 1,166 lines. Its KEEP tests run to about 2,600 lines (`caged-door` 510, `start-road` 377, `bridgehead` 401 for the stub, `cage` 308, `level1` 258, `read-tools` 170, `door-clear`/`door-spawn`/`besides`/`rewritten-event`/`reply-hook`/`pull-spawn-hook` about 450, and `index-tools` 88). Add `c/cloud-start` (202) over the same start road. `start-road`, `start`, `start-constants`, `hooks` (boot cases) and `c/cloud-start` all describe one start road; the next merge candidate is `c/cloud-start` into `start-road`.
- **Extension.** It is 3,346 lines of code against 4,706 lines of tests. After M4 the largest remaining tests are `sidebar` (527), `route-host` (394), `fields-to-fill` (384) and `lens` (382). Most cases rebuild a whole ticket through `v1-index.js`, so the R2 fix shrinks them too.
- **Person git hooks.** `precommit.test` (239) covers `precommit.js` (84). Its 13 cases run the private, tested and marker rules through the commit door, and `private.test`, `tested.test` and `markers.test` run the same rules at unit level.
- **Two live implementations of one rule set.** `private.js`, `tested.js`, `todo.js` and `trunk.js` still run in the person git hooks (JS), while `src/modules/hooks/command/*` runs them for the agent (Go), so each behavior is tested twice in two languages. The tests are not redundant while both runtimes exist. The duplication sits in the source, and ends if the git hooks call `se-index`.
""")
w("## Caveats\n")
w("""- Liveness is static. A function counts as live if any live function references it, so a few KEEP and REWRITE verdicts may still drive code that never runs in practice. The opposite error is unlikely for named imports. Strings built into dynamic `import()` calls were resolved by hand: the extension's three doors and `bridge/vehicle.js`.
- Copilot `dispatch` is a person-run, documented entry (`spec/design_output/copilot.md`), so the `work take` chain was treated as live. If it should leave too, M1 (2,780 lines) becomes DELETE, along with about 5.3k lines of `src/scripts/{work,pull,ticket}*` source.
- A deletion here leaves the dead source behind. 108 JS source modules (14,737 lines) are loaded from no entry, chiefly `src/bridge/*`, most of `.claude/skills/level0/lib/*` and most of `src/scripts/*`. They should leave with their tests. Otherwise `c/real-git` and the `tested.js` rule (\"every module tested\") will flag the orphans.
- MERGE means the behavior is worth one test, and the surviving copy is named above. Where that Go test already exists (M1, M3), the JS file can go as soon as the production thread named in the evidence is cut.
""")
open(S + "/test-audit-js.md", "w").write("\n".join(out))
print(json.dumps(tv)); print([ (f,L[f],A[f]) for f in dl])
