// Bundles the VS Code shell: vscode/src/extension.ts -> vscode/extension.js.
// The OUTPUT path is what the manifest, RUNME's copy and preflight's parse
// checks always pointed at — the migration moved the source, not the seam.
import { build } from "esbuild";

await build({
  entryPoints: ["vscode/src/extension.ts"],
  bundle: true,
  platform: "node",
  format: "cjs",
  target: "node18",
  external: ["vscode", "koffi"],
  outfile: "vscode/extension.js",
  banner: { js: "// GENERATED by esbuild from vscode/src/extension.ts — edit the source, then: npm run build" },
  logLevel: "info",
});
