// Builds the VS Code shell in two steps.
//
// ONE: bundle vscode/src/extension.ts -> vscode/extension.js. The OUTPUT path
// is what the manifest and preflight's parse check always pointed at.
//
// TWO: render the INSTALLABLE tree into vscode-dist/. That folder is generated,
// never committed, and carries the product's real name where the source keeps
// its $PRODUCT$ placeholders.
//
// WHY A SECOND FOLDER EXISTS AT ALL. VS Code loads extensions only from its own
// directory under the home folder. The repository is not that directory and
// nothing restructures it into one, so something has to put the extension
// there. RUNME links this folder into place, once.
//
// SO YOU ONLY EVER EDIT vscode/src. Both vscode/extension.js and vscode-dist/
// are output, and nothing reads them back.
//
// THE SOURCE KEEPS ITS $PRODUCT$ PLACEHOLDERS, which is what makes producing a
// vehicle a rename rather than a find-and-replace.
import { cpSync, rmSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { build } from "esbuild";
import { loadBrand, renderExtension } from "./engine/brand.ts";

const here = dirname(fileURLToPath(import.meta.url));
const root = dirname(here);

await build({
  entryPoints: ["vscode/src/extension.ts"],
  bundle: true,
  platform: "node",
  format: "cjs",
  target: "node18",
  external: ["vscode", "koffi"],
  outfile: "vscode/extension.js",
  banner: { js: "// GENERATED by esbuild from vscode/src/extension.ts — edit the source, then: npm run build" },
  logLevel: "info",
});

const dist = join(here, "vscode-dist");
// REBUILT FROM EMPTY. A file deleted from the source has to leave the install
// too, and only starting from nothing guarantees that.
rmSync(dist, { recursive: true, force: true });
cpSync(join(here, "vscode"), dist, {
  recursive: true,
  filter: (src) => !src.includes("node_modules"),
});
renderExtension(dist, loadBrand(root));
console.log(`  rendered ${dist}`);
