"""quack - the determinizer lane (deterministic; no judgment). Run via uv:
    uv run quack status [id] | next | why <id> | bless [--all|<id>] | note "..." | gather <ver> | ship
The high-level intent surface (note / engage / review) is slash-commands - see AGENTS.md.
"""
import os, sys, zipfile, datetime
from quackitect import engine

MARK = {"DONE": "[x]", "SUSPECT": "[~]", "OPEN": "[ ]"}

def _write_dashboard(rows):
    out = ["# Dashboard", "", "Derived - regenerated by `uv run quack status`.", "",
           "`[x]` done | `[~]` suspect (`quack why <id>`) | `[ ]` open", ""]
    for nid, st, cls in sorted(rows, key=lambda r: (r[1] != "SUSPECT", r[0])):
        out.append("- " + MARK[st] + " **" + nid + "** - " + st + " (" + cls + ")")
    n = sum(1 for _, s, _ in rows if s == "SUSPECT")
    out.append("\n_" + str(len(rows)) + " checks | " + str(n) + " suspect | generated " + str(datetime.date.today()) + "_")
    open(os.path.join(engine.ROOT, "DASHBOARD.md"), "w").write("\n".join(out))

def cmd_status(a):
    nodes = engine.load_all(); rows = engine.status(nodes)
    if a and not a[0].startswith("-"):
        for r in engine.why(nodes, a[0]):
            print(" -", r)
        return
    for nid, st, cls in sorted(rows, key=lambda r: (r[1] != "SUSPECT", r[0])):
        print(MARK[st] + " " + st.ljust(8) + " " + nid + "  (" + cls + ")")
    n = sum(1 for _, s, _ in rows if s == "SUSPECT")
    print("\n" + str(len(rows)) + " checks | " + str(n) + " suspect")
    _write_dashboard(rows)

def cmd_why(a):
    for r in engine.why(engine.load_all(), a[0]):
        print(" -", r)

def cmd_bless(a):
    t = a[0] if a else "--all"
    engine.bless(engine.load_all(), t); print("blessed", t)

def cmd_note(a):
    text = a[0] if a and not a[0].startswith("--") else input("note: ")
    origin = a[a.index("--origin") + 1] if "--origin" in a else None
    print("captured", os.path.basename(engine.add_note(text, origin)))

def cmd_ship(a):
    out = os.path.join(engine.QUACK, "out"); os.makedirs(out, exist_ok=True)
    z = os.path.join(out, "quackitect-v0.zip")
    with zipfile.ZipFile(z, "w", zipfile.ZIP_DEFLATED) as zf:
        for dp, _, fs in os.walk(os.path.join(engine.ROOT, "product")):
            if "__pycache__" in dp:
                continue
            for f in fs:
                fp = os.path.join(dp, f)
                zf.write(fp, os.path.relpath(fp, engine.ROOT))
    print("shipped", os.path.relpath(z, engine.ROOT), "- ephemeral output (not committed)")

def cmd_next(a):
    kind, node = engine.next_check(engine.load_all())
    if kind == "done":
        print("done - all gates green; /engage refine (default in late phases) or /engage ship."); return
    if kind == "blocked":
        print("blocked - no ready check (inspect the graph)."); return
    gate = ", GATE (human-adjudicated)" if node["killer"] else ""
    print("NEXT: " + node["id"] + "  (" + node["class"] + gate + ")")
    print("  " + node["statement"])
    if node["class"] == "executed":
        print("  verify: " + node["verify"])
    print("  -> fill it; gate -> ask the human to `uv run quack bless " + node["id"] + "`")

def cmd_gather(a):
    ver = a[0] if a else engine.config()["version"]
    path, n = engine.gather(ver)
    print("gathered " + str(n) + " source folder(s) -> " + os.path.relpath(path, engine.ROOT))
    print("  read it, open any flagged files / follow links, then COMPOSE the checklist")
    print("  as check nodes in spec/iterations/" + ver + "/ tailored to the idea, then bless.")

def cmd_report(a):
    out = "."
    if "--out" in a:
        out = a[a.index("--out") + 1]
    else:
        out = os.path.join(engine.QUACK, "out", "report.html")
    from quackitect import report
    path, model = report.write(out)
    done = sum(1 for s in model["smap"].values() if s == "DONE")
    print("report -> " + os.path.relpath(path, engine.ROOT)
          + "  (" + str(done) + "/" + str(len(model["nodes"])) + " done, root " + model["root"][:12] + ")")


CMDS = {"status": cmd_status, "why": cmd_why, "bless": cmd_bless, "note": cmd_note,
        "ship": cmd_ship, "next": cmd_next, "gather": cmd_gather, "report": cmd_report}

def main():
    cmd = sys.argv[1] if len(sys.argv) > 1 else "status"
    fn = CMDS.get(cmd)
    if not fn:
        print('determinizer: status [id] | next | why <id> | bless [--all|<id>] | note "..." | gather <ver> | report [--out F] | ship')
        print("methods (slash-commands): /note | /engage [start|next|refine|ship] | /review [readout|retro]")
        return
    fn(sys.argv[2:])

if __name__ == "__main__":
    main()
