// THE EDITOR EXTENSION'S BUILD OPTIONS, in ONE place.
//
// TWO CALLERS NEED THEM and they must not disagree. `esbuild.mjs` runs the real
// build. `tests/built-surface.test.ts` rebuilds in memory and compares, so that
// a committed file its source no longer produces is refused.
//
// A COPY WOULD DRIFT the day one side gains an option, and the guard would then
// fail saying the committed file is stale — which would be false, and the
// remedy it hands the reader would be wrong. A reviewer caught the copy before
// it had a chance to drift.
//
// WHY A .ts RATHER THAN LEAVING THEM IN THE .mjs: the typechecker cannot read a
// plain .mjs, so importing from there makes the test implicitly untyped. The
// build script already imports .ts modules, so this direction costs nothing.

/** What esbuild is told, minus where the output goes and how loud it is.
 *
 *  NOT `as const`. esbuild's own option type wants mutable arrays, so a frozen
 *  literal is rejected by the typechecker at the call site rather than here. */
export const VSCODE_BUILD: {
  entryPoints: string[];
  bundle: boolean;
  platform: "node";
  format: "cjs";
  target: string;
  external: string[];
  outfile: string;
  banner: { js: string };
} = {
  entryPoints: ["vscode/src/extension.ts"],
  bundle: true,
  platform: "node",
  format: "cjs",
  target: "node18",
  external: ["vscode", "koffi"],
  outfile: "vscode/extension.js",
  banner: { js: "// GENERATED by esbuild from vscode/src/extension.ts — edit the source, then: npm run build" },
};
