package main

import (
	"strings"
	"testing"
)

// THE READING VERB ANSWERS A RANGE, AN OUTLINE, AND A SHAPED SET.
//
// Reading was the one thing the verb table had no door for, so every read went
// out through a shell. These are the three shapes the door is for: a named
// range of a file, the headings of a note, and a set of files with the kinds
// the caller does not want left out of it.
func TestTheReadVerbAnswersANamedRange(t *testing.T) {
	t.Parallel()
	f := aTree(t)
	f.write("doc/a.md", "# One\n\nsomething\n\n## Two\n\nmore\n")

	got, err := TheReading(f.Roots, Reading{File: "doc/a.md", Lines: "3-5"})
	if err != nil {
		t.Fatal(err)
	}
	if len(got.Files) != 1 {
		t.Fatalf("one file was named and %d came back", len(got.Files))
	}
	one := got.Files[0]
	if one.Text != "something\n\n## Two\n" {
		t.Errorf("the range reads %q", one.Text)
	}
	if one.From != 3 || one.To != 5 || one.Of != 7 {
		t.Errorf("it answers lines %d to %d of %d, and the file holds seven", one.From, one.To, one.Of)
	}
}

// AND A NOTE IS OUTLINED BY ITS HEADINGS, which is how a reader finds the part
// worth reading whole.
func TestTheReadVerbOutlinesAMarkdownFile(t *testing.T) {
	t.Parallel()
	f := aTree(t)
	f.write("doc/a.md", "# One\n\nsomething\n\n## Two\n\nmore\n")

	got, err := TheReading(f.Roots, Reading{File: "doc/a.md", Outline: true})
	if err != nil {
		t.Fatal(err)
	}
	if len(got.Files) != 1 || len(got.Files[0].Outline) != 2 {
		t.Fatalf("a file with two headings outlined as %+v", got.Files)
	}
	if h := got.Files[0].Outline[0]; h.Line != 1 || h.Depth != 1 || h.Text != "One" {
		t.Errorf("the first heading reads %+v", h)
	}
	if h := got.Files[0].Outline[1]; h.Line != 5 || h.Depth != 2 || h.Text != "Two" {
		t.Errorf("the second heading reads %+v", h)
	}
	if got.Files[0].Text != "" {
		t.Errorf("an outline carried the lines as well: %q", got.Files[0].Text)
	}
}

// AND THE KINDS THE CALLER DOES NOT WANT ARE LEFT OUT, WITH WHY.
//
// A test, a generated file and a parked one are three things the engine already
// knows and every caller re-encodes by hand. What is dropped is named in the
// answer, because a set that is quietly short is worse than one nobody shaped.
func TestTheReadVerbLeavesOutTheKindsItIsTold(t *testing.T) {
	t.Parallel()
	f := aTree(t)
	f.write("src/x.go", "package x\n")
	f.write("src/x_test.go", "package x\n")
	f.write("src/_parked.go", "package x\n")
	f.write("src/made.go", "// Code generated by a machine. DO NOT EDIT.\npackage x\n")

	got, err := TheReading(f.Roots, Reading{Path: "src/*.go", Without: "tests,generated,parked"})
	if err != nil {
		t.Fatal(err)
	}
	if len(got.Files) != 1 || got.Files[0].Path != "src/x.go" {
		t.Fatalf("the shaping left %+v, and only src/x.go is none of the three", got.Files)
	}
	left := map[string]string{}
	for _, l := range got.LeftOut {
		left[l.Path] = l.Why
	}
	for path, why := range map[string]string{
		"src/x_test.go":  "test",
		"src/_parked.go": "parked",
		"src/made.go":    "generated",
	} {
		if !strings.Contains(left[path], why) {
			t.Errorf("%s was left out saying %q, and it is %s", path, left[path], why)
		}
	}
}
