package main

import (
	"bufio"
	"bytes"
	"encoding/json"
	"flag"
	"os"
)

// THE STUB. It is the lane between an agent and an engine, and it is
// deliberately small.
//
// It holds no rules. Everything it is asked, it asks the engine, and what the
// engine answers is what the agent gets. Which engine it talks to is decided
// where engines are listed, not compiled in here.
//
// It speaks JSON-RPC over standard input and output, one message per line,
// which is what the harnesses start.

var (
	method    = flag.String("method", "", "the method root (default: from the register)")
	work      = flag.String("work", "", "the folder being worked on (default: this one)")
	toolsFlag = flag.Bool("tools", false, "print the tools this door offers, as JSON, and exit")
)

type request struct {
	JSONRPC string          `json:"jsonrpc"`
	ID      json.RawMessage `json:"id,omitempty"`
	Method  string          `json:"method"`
	Params  json.RawMessage `json:"params,omitempty"`
}

type response struct {
	JSONRPC string  `json:"jsonrpc"`
	ID      any     `json:"id"`
	Result  any     `json:"result,omitempty"`
	Error   *rpcErr `json:"error,omitempty"`
}

type rpcErr struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

func main() {
	flag.Parse()
	// THE SNAPSHOT THE COLD DOOR ANSWERS FROM. util/cage/mcp-lane.mjs answers
	// tools/list off util/cage/tools.json before this program is built, so a
	// cold clone lists its tools in the first second rather than after a
	// build, and util/checks/mcp-tools.mjs holds that file against this list.
	if *toolsFlag {
		enc := json.NewEncoder(os.Stdout)
		enc.SetIndent("", "  ")
		_ = enc.Encode(map[string]any{
			"$comment": "GENERATED by .bin/se-mcp --tools > util/cage/tools.json. Edit src/mcp/lane.go, not this file.",
			"tools":    tools(),
		})
		return
	}
	roots := findRoots()

	in := bufio.NewScanner(os.Stdin)
	in.Buffer(make([]byte, 0, 1<<20), 1<<24)
	out := json.NewEncoder(os.Stdout)

	for in.Scan() {
		line := in.Bytes()
		if len(line) == 0 {
			continue
		}
		var req request
		if err := json.Unmarshal(line, &req); err != nil {
			continue // a line that is not a message is not ours to complain about
		}
		// A notification has no id and takes no answer.
		if len(req.ID) == 0 {
			continue
		}
		var id any
		_ = json.Unmarshal(req.ID, &id) // an id that will not read is a notification, which has none

		switch req.Method {
		case "initialize":
			// The client's version is echoed back. Choosing one here is how a
			// stub stops working when a harness moves on.
			var p struct {
				ProtocolVersion string `json:"protocolVersion"`
			}
			_ = json.Unmarshal(req.Params, &p) // params that will not read are no params
			if p.ProtocolVersion == "" {
				p.ProtocolVersion = "2025-06-18"
			}
			reply(out, id, map[string]any{
				"protocolVersion": p.ProtocolVersion,
				"capabilities":    map[string]any{"tools": map[string]any{}},
				"serverInfo":      map[string]any{"name": "quackitect", "version": "0.1.0"},
			})
		case "tools/list":
			reply(out, id, map[string]any{"tools": tools()})
		case "tools/call":
			reply(out, id, call(roots, req.Params))
		case "ping":
			reply(out, id, map[string]any{})
		default:
			out.Encode(response{JSONRPC: "2.0", ID: id,
				Error: &rpcErr{Code: -32601, Message: "no such method: " + req.Method}})
		}
	}
}

func reply(out *json.Encoder, id any, result any) {
	_ = out.Encode(response{JSONRPC: "2.0", ID: id, Result: result}) // the pipe is shut, so there is nobody left to tell
}

// tools is every tool this door offers.
//
// IT IS THE LANE AND NOTHING BESIDE IT. Three tools were appended here after
// laneTools(), outside the table TestToolSchemasComeFromTheirStructs walks, so
// the drift the guard exists to end stayed open for exactly the tools it could
// not see: se_status still wrote its schema as a literal, and se_answer and
// se_said advertised a struct with nothing holding it against the handler that
// decodes the arguments. A tool declared anywhere but the table is a tool no
// guard reads.
func tools() []map[string]any {
	return laneTools()
}

func call(roots roots, params json.RawMessage) map[string]any {
	var p struct {
		Name      string          `json:"name"`
		Arguments json.RawMessage `json:"arguments"`
	}
	_ = json.Unmarshal(params, &p) // params that will not read are no params

	switch p.Name {
	case "se_start":
		return text(taking(roots, p.Arguments, startTheEngine))
	case "se_status":
		return text(taking(roots, p.Arguments, showStatus))
	case "se_answer":
		return text(taking(roots, p.Arguments, recordAnswer))
	case "se_said":
		return text(taking(roots, p.Arguments, recordSaid))
	case "se_test":
		return text(taking(roots, p.Arguments, testTheDelta))
	case "se_claim":
		return text(taking(roots, p.Arguments, claimWork))
	case "se_find":
		return text(taking(roots, p.Arguments, findInTree))
	case "se_ask":
		return text(taking(roots, p.Arguments, askIndex))
	case "se_apply":
		return text(taking(roots, p.Arguments, applyEdits))
	case "se_run":
		return text(taking(roots, p.Arguments, runCommand))
	case "se_work":
		return text(taking(roots, p.Arguments, mintWork))
	case "se_pull":
		return text(taking(roots, p.Arguments, pull))
	case "se_stop":
		return text(taking(roots, p.Arguments, stopClaim))
	}
	return text("No such tool: " + p.Name)
}

// taking decodes the arguments into the request the handler declares, and
// hands them over.
//
// THE TYPE IS THE ONE THE DOOR ADVERTISED. schema.go reads the same struct for
// the schema an agent is shown, so what the agent is invited to send is what
// the handler reads, and neither list can move without the other.
func taking[T any](r roots, raw json.RawMessage, f func(roots, T) string) string {
	var a T
	if len(raw) > 0 && string(raw) != "null" {
		// A FIELD THIS TOOL DOES NOT TAKE IS REFUSED, NOT DISCARDED.
		// json.Unmarshal drops one without a word, so a call naming the actor
		// as by decoded to nothing, the actor fell back to main, and the write
		// was filed under a name the caller never chose. The caller found out
		// from a later refusal about a holder, two calls away from the cause.
		//
		// THE REFUSAL NAMES THE FIELDS THIS TOOL TAKES, off the same struct the
		// advertised schema is read off, so the correction is one word.
		d := json.NewDecoder(bytes.NewReader(raw))
		d.DisallowUnknownFields()
		if err := d.Decode(&a); err != nil {
			return fail("the arguments will not read: " + err.Error() +
				". This tool takes: " + theFieldsItTakes(a))
		}
	}
	return f(r, a)
}

func text(s string) map[string]any {
	return map[string]any{"content": []map[string]any{{"type": "text", "text": s}}}
}
