// GENERATED by esbuild from vscode/src/extension.ts — edit the source, then: npm run build
"use strict";
var __getOwnPropNames = Object.getOwnPropertyNames;
var __commonJS = (cb, mod) => function __require() {
  try {
    return mod || (0, cb[__getOwnPropNames(cb)[0]])((mod = { exports: {} }).exports, mod), mod.exports;
  } catch (e) {
    throw mod = 0, e;
  }
};

// vscode/src/keys.js
var require_keys = __commonJS({
  "vscode/src/keys.js"(exports2, module2) {
    "use strict";
    var VK = {
      RETURN: 13,
      CONTROL: 17,
      V: 86
    };
    var INPUT_KEYBOARD = 1;
    var KEYEVENTF_KEYUP = 2;
    var loaded;
    function bind() {
      if (loaded !== void 0) return loaded;
      loaded = null;
      if (process.platform !== "win32") return loaded;
      try {
        const koffi = require("koffi");
        const user32 = koffi.load("user32.dll");
        const KEYBDINPUT = koffi.struct("SeKEYBDINPUT", {
          wVk: "uint16",
          wScan: "uint16",
          dwFlags: "uint32",
          time: "uint32",
          dwExtraInfo: "uintptr"
        });
        const MOUSEINPUT = koffi.struct("SeMOUSEINPUT", {
          dx: "int32",
          dy: "int32",
          mouseData: "uint32",
          dwFlags: "uint32",
          time: "uint32",
          dwExtraInfo: "uintptr"
        });
        const UNION = koffi.union("SeINPUTUNION", { mi: MOUSEINPUT, ki: KEYBDINPUT });
        const INPUT = koffi.struct("SeINPUT", { type: "uint32", u: UNION });
        const SendInput = user32.func("uint32 __stdcall SendInput(uint32 cInputs, SeINPUT *pInputs, int cbSize)");
        loaded = { koffi, INPUT, SendInput };
      } catch {
        loaded = null;
      }
      return loaded;
    }
    function available() {
      return bind() !== null;
    }
    function event(vk, up) {
      return {
        type: INPUT_KEYBOARD,
        u: { ki: { wVk: vk, wScan: 0, dwFlags: up ? KEYEVENTF_KEYUP : 0, time: 0, dwExtraInfo: 0 } }
      };
    }
    function tap(vk, modifiers = []) {
      const bound = bind();
      if (bound === null) return 0;
      const events = [];
      for (const m of modifiers) events.push(event(m, false));
      events.push(event(vk, false), event(vk, true));
      for (const m of [...modifiers].reverse()) events.push(event(m, true));
      try {
        return bound.SendInput(events.length, events, bound.koffi.sizeof(bound.INPUT));
      } catch {
        return 0;
      }
    }
    var paste = () => tap(VK.V, [VK.CONTROL]);
    var enter = () => tap(VK.RETURN);
    module2.exports = { available, tap, paste, enter, VK };
  }
});

// vscode/src/extension.ts
var vscode = require("vscode");
var { spawn, spawnSync } = require("node:child_process");
var keys = require_keys();
var { appendFileSync, copyFileSync, existsSync, mkdirSync, readFileSync, statSync, writeFileSync } = require("node:fs");
var path = require("node:path");
var PORT = 7333;
var SERVER = `http://localhost:${PORT}`;
var SLOTS = 8;
var VIEW_TYPE = (slot) => `$PRODUCT_ID$.card${slot}`;
var POLL_MS = 1e3;
var BUILD = "unknown";
var child = null;
var output = null;
var disposed = false;
var serverJustStarted = false;
var cards = [];
var levels = null;
var packet = null;
var strip = null;
var controls = null;
var detailsView = null;
var poller = null;
var busyDone = null;
var agentTerm = null;
var agentStarting = false;
var logTerm = null;
var logEmitter = null;
var logRows = [];
var logFilter = "";
var logAnchored = false;
var lastWalk = "";
var engineUp = false;
var logSeen = /* @__PURE__ */ new Set();
var lastDetails = null;
var snapshots = /* @__PURE__ */ new Set();
var windows = /* @__PURE__ */ new Map();
var sessionToken = `${process.pid}-${Date.now().toString(36)}`;
var traceFile = null;
function trace(what) {
  try {
    if (traceFile === null) {
      const root = projectRoot();
      if (root === null) return;
      mkdirSync(path.join(root, ".se"), { recursive: true });
      traceFile = path.join(root, ".se", "vscode-debug.log");
    }
    appendFileSync(traceFile, `${(/* @__PURE__ */ new Date()).toISOString().slice(11, 23)} ${what}
`);
  } catch {
  }
}
function projectRoot() {
  const isRoot = (p) => existsSync(path.join(p, "project", "deliverable", "engine", "bin", "se-mcp.ts"));
  for (const f of vscode.workspace.workspaceFolders ?? []) {
    const p = f.uri.fsPath;
    if (isRoot(p)) return p;
    const up = path.dirname(p);
    if (isRoot(up)) return up;
  }
  return null;
}
function nodeRunner() {
  const probe = spawnSync("node", ["--version"], { encoding: "utf8", shell: process.platform === "win32" });
  if (probe.status === 0) {
    const v = String(probe.stdout).trim().replace(/^v/, "").split(".").map(Number);
    if (v[0] > 22 || v[0] === 22 && v[1] >= 6) return { cmd: "node", shell: true, env: {} };
  }
  const own = process.versions.node.split(".").map(Number);
  if (own[0] > 22 || own[0] === 22 && own[1] >= 6) {
    return { cmd: process.execPath, shell: false, env: { ELECTRON_RUN_AS_NODE: "1" } };
  }
  return null;
}
function listeningPids(port) {
  if (!Number.isFinite(port) || port <= 0) return [];
  if (process.platform === "win32") {
    const script = `$p=${port}; Get-NetTCPConnection -State Listen -LocalPort $p -ErrorAction SilentlyContinue | Select-Object -ExpandProperty OwningProcess -Unique`;
    const r = spawnSync("powershell", ["-NoProfile", "-Command", script], { encoding: "utf8", windowsHide: true });
    if (r.status !== 0) return [];
    return String(r.stdout ?? "").split(/\r?\n/).map((s) => Number(s.trim())).filter((n) => Number.isInteger(n) && n > 0);
  }
  const lsof = spawnSync("lsof", ["-nP", `-iTCP:${port}`, "-sTCP:LISTEN", "-t"], { encoding: "utf8" });
  if (lsof.status !== 0) return [];
  return String(lsof.stdout ?? "").split(/\r?\n/).map((s) => Number(s.trim())).filter((n) => Number.isInteger(n) && n > 0);
}
function evictPort(port) {
  const killed = [];
  for (const pid of listeningPids(port)) {
    if (!Number.isInteger(pid) || pid <= 0) continue;
    if (pid === process.pid || pid === process.ppid) continue;
    try {
      if (process.platform === "win32") {
        const r = spawnSync("taskkill", ["/PID", String(pid), "/T", "/F"], { encoding: "utf8", windowsHide: true });
        if (r.status === 0) killed.push(pid);
      } else {
        process.kill(pid, "SIGTERM");
        killed.push(pid);
      }
    } catch {
    }
  }
  return [...new Set(killed)].sort((a, b) => a - b);
}
function placeConfigs(root) {
  const opened = path.join(root, "project");
  const cage = path.join(opened, "_cage");
  const place = (src, destDir, destName) => {
    mkdirSync(destDir, { recursive: true });
    copyFileSync(path.join(cage, src), path.join(destDir, destName));
  };
  place("mcp-http.json", opened, ".mcp.json");
  place("mcp-http.json", path.join(opened, ".copilot"), "mcp-config.json");
  place("vscode-mcp.json", path.join(opened, ".vscode"), "mcp.json");
  place("vscode-instructions.md", path.join(opened, ".github"), "copilot-instructions.md");
  place("claude-settings.json", path.join(opened, ".claude"), "settings.json");
  placeVoiceProjections(root, opened);
  placePromptLayer(root, opened);
}
function placePromptLayer(root, opened) {
  const script = path.join(root, "project", "deliverable", "engine", "bin", "place-prompt-layer.ts");
  const r = spawnSync("node", [script, "--root", root, "--opened", opened], {
    encoding: "utf8",
    shell: process.platform === "win32",
    windowsHide: true
  });
  if (r.status !== 0) trace(`prompt layer not placed: ${String(r.stderr || r.stdout).trim()}`);
}
function placeVoiceProjections(root, opened) {
  const write = (dir, name, head, body) => {
    mkdirSync(dir, { recursive: true });
    writeFileSync(path.join(dir, name), `${head.join("\n")}

${body}`, "utf8");
  };
  const GENERATED = "description: Generated from project/guidance/voice.md. Edit that file, never this one.";
  try {
    const voice = readFileSync(path.join(root, "project", "guidance", "voice.md"), "utf8");
    write(path.join(opened, ".claude", "output-styles"), "voice.md", ["---", "name: voice", GENERATED, "---"], voice);
  } catch (e) {
    trace(`voice projections not placed: ${String(e?.message)}`);
  }
}
async function api(pathname, init) {
  try {
    const r = await fetch(SERVER + pathname, { signal: AbortSignal.timeout(2500), ...init });
    if (!r.ok) return null;
    return await r.json();
  } catch {
    return null;
  }
}
var post = (pathname, body) => api(pathname, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) });
async function probeServer() {
  const body = await api("/api/alive");
  engineUp = body !== null;
  if (body === null) return { state: "down" };
  return { state: "up", root: typeof body.root === "string" ? body.root : null };
}
function ensureDeps(root) {
  const deliverable = path.join(root, "project", "deliverable");
  if (existsSync(path.join(deliverable, "node_modules"))) return Promise.resolve(true);
  return vscode.window.withProgress(
    { location: vscode.ProgressLocation.Notification, title: "$PRODUCT$: first run \u2014 installing engine dependencies" },
    () => new Promise((resolve) => {
      const npm = spawn("npm", ["install", "--no-audit", "--no-fund", "--loglevel=error"], { cwd: deliverable, shell: true });
      npm.stdout.on("data", (d) => output.append(String(d)));
      npm.stderr.on("data", (d) => output.append(String(d)));
      npm.on("error", () => resolve(false));
      npm.on("exit", (code) => resolve(code === 0));
    })
  );
}
function startServer(root, runner) {
  const entry = path.join(root, "project", "deliverable", "engine", "bin", "se-mcp.ts");
  child = spawn(runner.cmd, [entry, "--root", root, "--child", "--headless"], {
    cwd: root,
    env: { ...process.env, ...runner.env, SE_SESSION: sessionToken, SE_PARENT_PID: String(process.pid), SE_PANEL_SUPPRESS: "1" },
    stdio: ["ignore", "pipe", "pipe"],
    shell: runner.shell,
    windowsHide: true
  });
  child.stdout.on("data", (d) => output.append(String(d)));
  child.stderr.on("data", (d) => output.append(String(d)));
  child.on("exit", (code) => {
    child = null;
    if (disposed) return;
    if (code === 42) {
      output.appendLine("se: reload ordered \u2014 respawning the engine");
      setTimeout(() => {
        if (!disposed) startServer(root, runner);
      }, 100);
    } else {
      output.appendLine(`se: engine exited (${code})`);
    }
  });
}
async function ensureServer() {
  const root = projectRoot();
  if (root === null) {
    void vscode.window.showErrorMessage("$PRODUCT$: open the project's product folder (or the project root) first.");
    return false;
  }
  placeConfigs(root);
  serverJustStarted = false;
  const probe = await probeServer();
  if (probe.state === "up") {
    if (probe.root !== null && path.resolve(probe.root) !== path.resolve(root)) {
      const killed = evictPort(PORT);
      if (killed.length > 0) {
        output.appendLine(`se: mirror port ${PORT} was occupied by another project; stopped pid(s) ${killed.join(", ")}`);
        await new Promise((r) => setTimeout(r, 250));
      } else {
        void vscode.window.showErrorMessage(
          `$PRODUCT$: port ${PORT} already serves another project (${probe.root}) and could not be reclaimed automatically.`
        );
        return false;
      }
    } else {
      return true;
    }
  }
  const runner = nodeRunner();
  if (runner === null) {
    void vscode.window.showErrorMessage("$PRODUCT$ needs Node 22.6 or newer \u2014 install it, then retry: winget install OpenJS.NodeJS.LTS");
    return false;
  }
  if (!await ensureDeps(root)) {
    void vscode.window.showErrorMessage("$PRODUCT$: npm install failed \u2014 details in Output \u2192 $PRODUCT$ Engine.");
    return false;
  }
  const squatters = evictPort(PORT);
  if (squatters.length > 0) {
    output.appendLine(`se: mirror port ${PORT} was held by pid(s) ${squatters.join(", ")} \u2014 stopped them`);
    await new Promise((r) => setTimeout(r, 250));
  }
  startServer(root, runner);
  serverJustStarted = true;
  for (let i = 0; i < 75; i++) {
    if ((await probeServer()).state === "up") return true;
    await new Promise((r) => setTimeout(r, 200));
  }
  void vscode.window.showErrorMessage("$PRODUCT$: the engine did not come up \u2014 details in Output \u2192 $PRODUCT$ Engine.");
  return false;
}
var bar = "";
async function fetchBar() {
  try {
    const r = await fetch(`${SERVER}/widget/controls`);
    return r.ok === true ? await r.text() : "";
  } catch {
    return "";
  }
}
async function fetchCards() {
  const body = await api("/api/cards");
  return body !== null && Array.isArray(body.cards) ? body.cards : [];
}
var shown = (c) => c !== void 0 && c.widget !== "terminal";
var inStrip = (c) => shown(c) && c.widget !== "details";
var cardBySlot = (n) => cards.find((c) => c.n === n);
var detailsCard = () => cards.find((c) => c.widget === "details");
async function refreshCards() {
  cards = await fetchCards();
  if (strip !== null) strip.render();
  for (const w of windows.values()) w.render();
}
async function ensureCards() {
  if (cards.length === 0) await refreshCards();
}
function titleOf(card) {
  return card.title.charAt(0).toUpperCase() + card.title.slice(1);
}
async function pollWalk() {
  if (levels === null) levels = await api("/api/levels");
  const p = await api("/api/packet");
  if (p === null) return;
  const moved = `${JSON.stringify(p.active ?? null)}|${String(p.status)}` !== lastWalk;
  lastWalk = `${JSON.stringify(p.active ?? null)}|${String(p.status)}`;
  packet = p;
  bar = await fetchBar();
  if (controls !== null) controls.send();
  if (logTerm !== null) await pollLog();
  if (moved) {
    if (detailsView !== null) detailsView.post({ se: "wake" });
    for (const w of windows.values()) w.post({ se: "wake" });
  }
}
function startPolling() {
  if (poller !== null) return;
  poller = setInterval(() => void pollWalk(), POLL_MS);
  void pollWalk();
}
function escapeHtml(s) {
  return String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}
function messagePage(text) {
  return `<!DOCTYPE html><html><head><meta charset="utf-8"><style>
  body { font-family: var(--vscode-font-family); font-size: var(--vscode-font-size); color: var(--vscode-descriptionForeground); margin: 0; padding: 10px 12px; }
</style></head><body>${escapeHtml(text)}</body></html>`;
}
function framePage(url) {
  return `<!DOCTYPE html><html><head><meta charset="utf-8">
<meta http-equiv="Content-Security-Policy" content="default-src 'none'; frame-src ${SERVER}; connect-src ${SERVER}; script-src 'unsafe-inline'; style-src 'unsafe-inline'">
<style>
  html, body { margin: 0; padding: 0; width: 100%; height: 100%; overflow: hidden; background: var(--vscode-editor-background); }
  iframe { border: 0; width: 100%; height: 100%; display: none; }
  #wait { font-family: var(--vscode-font-family); font-size: var(--vscode-font-size); color: var(--vscode-descriptionForeground); padding: 10px 12px; }
  #hint { margin-top: 6px; display: none; }
</style></head><body>
<div id="wait">Starting the engine\u2026<div id="hint"></div></div>
<iframe id="frame"></iframe>
<script>
  // THE ENGINE IS USUALLY ALREADY UP by the time a card is opened. Waiting for
  // a round trip to rediscover that put a visible pause in front of every
  // card. When the host already knows, the page starts loading at once.
  const START_NOW = ${engineUp ? "true" : "false"};
  const vsapi = acquireVsCodeApi();
  window.addEventListener("error", (e) => vsapi.postMessage({ se: "trace", text: "host page ERROR " + (e.message || "?") }));
  const SERVER = ${JSON.stringify(SERVER)};
  const PAGE = ${JSON.stringify(url)};
  const frame = document.getElementById("frame");
  const wait = document.getElementById("wait");
  const hint = document.getElementById("hint");
  const cssVar = (n) => getComputedStyle(document.body).getPropertyValue(n).trim();
  // The editor's palette AND its fonts travel in: inside the iframe no
  // --vscode-* variable exists, so every one the skin reads is forwarded.
  function themeVars() {
    return {
      "--se-bg": cssVar("--vscode-editor-background"),
      "--se-bg-side": cssVar("--vscode-sideBar-background"),
      "--se-raised": cssVar("--vscode-editorWidget-background"),
      "--se-border": cssVar("--vscode-editorWidget-border") || cssVar("--vscode-panel-border"),
      "--se-border-strong": cssVar("--vscode-scrollbarSlider-background"),
      "--se-fg": cssVar("--vscode-editor-foreground"),
      "--se-muted": cssVar("--vscode-descriptionForeground"),
      "--se-dim": cssVar("--vscode-disabledForeground"),
      "--vscode-font-family": cssVar("--vscode-font-family"),
      "--vscode-editor-font-family": cssVar("--vscode-editor-font-family"),
      // The MEANINGS the drawing maps to. Not every theme defines the testing
      // colour, so the chart green stands in rather than nothing at all.
      "--vscode-button-background": cssVar("--vscode-button-background"),
      // The walk's blue. The editor names no colour for "where the walk is",
      // so a theme without a chart palette falls back in the sheet itself.
      "--vscode-charts-blue": cssVar("--vscode-charts-blue"),
      "--vscode-testing-iconPassed": cssVar("--vscode-testing-iconPassed") || cssVar("--vscode-charts-green"),
      "--vscode-editorWarning-foreground": cssVar("--vscode-editorWarning-foreground"),
    };
  }
  let pendingHelp = null;
  // LOADED IS NOT THE SAME AS UP. "up" only means the engine answered; the
  // iframe still has to fetch and parse its page. Posting between the two
  // delivered into a document that was about to be replaced, which is why an
  // expanded snapshot arrived with a title and nothing under it.
  let loaded = false;
  function sendTheme() {
    if (frame.contentWindow) frame.contentWindow.postMessage({ se: "theme", vars: themeVars() }, "*");
  }
  frame.addEventListener("load", () => {
    loaded = true;
    sendTheme();
    setTimeout(sendTheme, 400);
    if (pendingHelp !== null) {
      // It stays pending until the page ACKNOWLEDGES it, so a document that is
      // replaced again mid-delivery still gets the subject on the next load.
      const h = pendingHelp;
      setTimeout(() => frame.contentWindow && frame.contentWindow.postMessage(h, "*"), 450);
    }
  });
  let up = false;
  function show() {
    if (up) return;
    up = true;
    frame.src = PAGE;
    wait.style.display = "none";
    frame.style.display = "block";
  }
  window.addEventListener("message", (ev) => {
    const d = ev.data;
    if (!d) return;
    if (d.se === "open") { vsapi.postMessage(d); return; }
    if (d.se === "trace") { vsapi.postMessage(d); return; } // the page reporting what it just did
    if (d.se === "details") { vsapi.postMessage(d); return; } // a click in THIS card, bound for the details group
    if (d.se === "open-form") { vsapi.postMessage(d); return; } // a form wants its own panel
    if (d.se === "theme-changed") { sendTheme(); return; }
    if (d.se === "up") { show(); return; }
    if (d.se === "wake") { if (loaded && frame.contentWindow) frame.contentWindow.postMessage(d, "*"); return; }
    // THE PAGE ACKNOWLEDGES, AND UNTIL IT DOES THE SUBJECT STAYS PENDING.
    // The loaded flag only says that a document once finished loading. It
    // says nothing about the one being replaced right this moment, and a
    // post into a dying document is swallowed silently.
    // NO BACKTICKS ANYWHERE IN HERE: this block lives inside a template
    // literal, and one backtick ends the string. It shipped broken once.
    if (d.se === "ack") { pendingHelp = null; return; }
    if (d.se === "nav") { loaded = false; return; }
    if (d.se === "help" || d.se === "logref") {
      vsapi.postMessage({ se: "trace", text: "relay " + d.se + " loaded=" + loaded + " frame=" + (frame.contentWindow ? "yes" : "no") });
      pendingHelp = d;
      if (loaded && frame.contentWindow) frame.contentWindow.postMessage(d, "*");
      show();
      // AND IF NOTHING COMES BACK, THE PAGE IS GONE \u2014 whatever the reason.
      // Seen live 2026-07-30: delivery stopped at 19:42 and never resumed,
      // with no navigation in between, while the relay still read loaded=true.
      // Reloading the frame re-delivers on load. It is the one recovery that
      // does not depend on knowing why the page went quiet. One reload per
      // subject, never a loop: the load path re-posts without re-arming this.
      const mine = d;
      setTimeout(() => {
        if (pendingHelp !== mine) return;
        vsapi.postMessage({ se: "trace", text: "relay unacked after 800ms \u2014 reloading the frame" });
        loaded = false;
        frame.src = PAGE;
      }, 800);
    }
  });
  // TWO WAKE PATHS, deliberately. The extension host probes over Node, where
  // no origin rule applies. This page probes too, as a backstop. Whichever
  // lands first reveals the surface; the reader never watches a dead line.
  if (START_NOW) show();
  (async function boot() {
    const started = Date.now();
    for (;;) {
      if (up) return;
      try {
        const r = await fetch(SERVER + "/api/alive");
        if (r.ok) { show(); return; }
      } catch { /* not up yet */ }
      if (Date.now() - started > 10000 && hint.style.display === "none") {
        hint.style.display = "block";
        hint.textContent = "Still starting. Output \u2192 $PRODUCT$ Engine has the details.";
      }
      await new Promise((r) => setTimeout(r, 500));
    }
  })();
</script></body></html>`;
}
var ICON = {
  help: '<svg viewBox="0 0 16 16"><circle cx="8" cy="8" r="6.2"/><path d="M6.2 6.1a1.85 1.85 0 1 1 2.1 2.2v1.1" /><circle cx="8.3" cy="11.4" r=".75" fill="currentColor" stroke="none"/></svg>',
  play: '<svg viewBox="0 0 16 16"><path d="M4.2 2.6 13 8l-8.8 5.4z" fill="currentColor" stroke="none"/></svg>',
  machine: '<svg viewBox="0 0 16 16"><circle cx="3.4" cy="8" r="1.9"/><circle cx="12.6" cy="4.2" r="1.9"/><circle cx="12.6" cy="11.8" r="1.9"/><path d="M5.2 7.3 10.8 4.9M5.2 8.7l5.6 2.4"/></svg>',
  graph: '<svg viewBox="0 0 16 16"><path d="M2.2 2.4v11.2h11.6"/><path d="M4.4 11.2 7 7.1l2.4 2.3 3.6-5"/></svg>',
  book: '<svg viewBox="0 0 16 16"><path d="M2.4 3.1h3.9c.9 0 1.6.4 1.7.9.1-.5.8-.9 1.7-.9h3.9v9.3H9.7c-.9 0-1.6.4-1.7.9-.1-.5-.8-.9-1.7-.9H2.4z"/><path d="M8 4v9.3"/></svg>',
  log: '<svg viewBox="0 0 16 16"><path d="M2.6 4.2h10.8M2.6 8h10.8M2.6 11.8h6.8"/></svg>',
  card: '<svg viewBox="0 0 16 16"><rect x="2.6" y="2.6" width="10.8" height="10.8"/></svg>',
  restart: '<svg viewBox="0 0 16 16"><path d="M13.2 8a5.2 5.2 0 1 1-1.7-3.85"/><path d="M13.6 1.9v3.3h-3.3"/></svg>'
};
function cardIcon(card) {
  if (card.widget === "machine") return ICON.machine;
  if (card.widget === "log") return ICON.log;
  if (card.id.indexOf("graph") >= 0) return ICON.graph;
  if (card.id.indexOf("book") >= 0) return ICON.book;
  return ICON.card;
}
var systemHelp = () => `<p><b>Shell build ${escapeHtml(BUILD)}</b> \u2014 if this is older than the fix you are testing, the window was not reloaded.</p>
<p>$PRODUCT$ walks a state machine with you. The machine says which step is in hand, what to read, and what to produce.</p>
<p>The engine runs on this computer only. Nothing leaves it.</p>
<p>The sidebar has three groups. Features is what you can do. Controls steers the walk. Details is this \u2014 whatever you click explains itself here.</p>
<p>Every card except this one opens as its own editor window. Split it, drag it to any side, or move it to a second window.</p>
<p>VS Code remembers that layout for this folder. Open the folder again and your windows come back where you left them.</p>
<p>The play button starts Claude in a terminal, or opens Copilot in Chat agent mode, with the opening prompt already sent.</p>
<p>Several agents may attach at once. Give the wheel to one at a time.</p>`;
function cardHelp(card) {
  if (!card.widget) {
    return `<p><b>${escapeHtml(titleOf(card))}</b> is card ${card.n}, and it is not built yet.</p>
<p>The slot is held so the card numbers never shift under your hand.</p>`;
  }
  const what = {
    machine: "The machine being walked. Each box is a state; the blue line is where the walk is aimed. Click a state to read it here. The crumbs along its top navigate between machines.",
    log: "Every act in this session, newest first. Click a line to see what it changed. It opens beside the agent's terminal.",
    details: "This group. Whatever you click elsewhere explains itself here."
  };
  return `<p><b>${escapeHtml(titleOf(card))}</b> is card ${card.n}.</p>
<p>${escapeHtml(what[card.widget] ?? "A card of the control panel.")}</p>
<p>Open it with ctrl+alt+${card.n}. It is an editor window, so put it wherever you like; VS Code remembers.</p>`;
}
var HELP = {
  "$PRODUCT_ID$.startAgent": {
    title: "Start the agent",
    html: `<p>Starts the engine if it is not running, then launches your agent.</p>
<p>Claude opens in the side bar. If that fails it falls back to a terminal.</p>
<p>Copilot tries to start in Chat agent mode with the same kickoff prompt and mapped tool exclusions; if unavailable, it falls back to terminal launch.</p>
<p>The log opens beside the active terminal when one exists.</p>
<p>A terminal or Chat launch is sent the opening prompt for you. A side-bar launch is not: Claude Code accepts no prompt through a command, and the agent's instructions start it unasked.</p>
<p>Claude Code is used when it is installed; otherwise the Copilot CLI, in its cage.</p>`
  }
};
function openInEditor(rel) {
  const root = projectRoot();
  if (root === null || typeof rel !== "string" || rel === "") return;
  const abs = path.normalize(path.join(root, ...rel.split("/")));
  if (!abs.startsWith(path.normalize(root))) return;
  void vscode.commands.executeCommand("vscode.open", vscode.Uri.file(abs), { preview: false });
}
function setBusy(on, label) {
  if (busyDone !== null) {
    busyDone();
    busyDone = null;
  }
  if (on !== true) return;
  void vscode.window.withProgress(
    { location: vscode.ProgressLocation.Notification, title: label === "" ? "$PRODUCT$" : label },
    () => new Promise((resolve) => {
      busyDone = resolve;
      setTimeout(() => {
        if (busyDone === resolve) {
          busyDone = null;
          resolve();
        }
      }, 2e4);
    })
  );
}
function onWebviewMessage(m) {
  if (!m) return;
  if (m.se === "trace") {
    trace(`page: ${String(m.text ?? "")}`);
    return;
  }
  trace(`webview: ${String(m.se)}`);
  if (m.se === "open") openInEditor(m.path);
  else if (m.se === "busy") setBusy(m.on === true, String(m.label ?? ""));
  else if (m.se === "details") void showHelp(m.title, m.html, false);
  else if (m.se === "open-form") openFormPanel(String(m.name ?? ""));
}
async function handleBarHelp(m) {
  if (m.se === "field-help") {
    await showFieldHelp(m.which);
    return true;
  }
  if (m.se === "scale-help") {
    await showScaleHelp(m.which, m.level);
    return true;
  }
  if (m.se === "row-help") {
    const safe = String(m.text ?? "").replace(/&/g, "&amp;").replace(/</g, "&lt;");
    await showHelp(String(m.label ?? "row"), `<p>${safe}</p>`, false);
    return true;
  }
  return false;
}
function openFormPanel(name) {
  if (name === "") return;
  const panel = vscode.window.createWebviewPanel("seForm", `form \xB7 ${name}`, vscode.ViewColumn.Beside, { enableScripts: true });
  const src = `${SERVER}/widget/details?embed=1&detail=${encodeURIComponent(`form:${name}`)}`;
  panel.webview.html = `<!doctype html><html><body style="margin:0;padding:0;height:100vh"><iframe src="${src}" style="border:0;width:100%;height:100%"></iframe></body></html>`;
}
var Surface = class {
  constructor(page) {
    this.page = page;
    this.web = null;
    this.lastHtml = null;
  }
  attach(webview, onReady) {
    this.web = webview;
    webview.options = { enableScripts: true };
    webview.onDidReceiveMessage(onWebviewMessage);
    this.render();
    void ensureServer().then(async (ok) => {
      if (!ok) return;
      await ensureCards();
      this.render();
      this.up();
      if (typeof onReady === "function") onReady();
    });
  }
  render() {
    if (this.web === null) return;
    const html = this.page();
    if (html === this.lastHtml) return;
    this.lastHtml = html;
    this.web.html = html;
  }
  post(msg) {
    if (this.web !== null) void this.web.postMessage(msg);
  }
  up() {
    this.post({ se: "up" });
  }
  theme() {
    this.post({ se: "theme-changed" });
  }
  help(title, html) {
    this.post({ se: "help", title, html });
  }
};
var CardView = class extends Surface {
  constructor(widget) {
    super(() => framePage(`${SERVER}/widget/${widget}?embed=1`));
  }
  resolveWebviewView(view) {
    view.onDidDispose(() => {
      this.web = null;
    });
    this.attach(view.webview);
  }
};
var CardWindow = class extends Surface {
  constructor(slot, panel) {
    super(() => {
      const card = cardBySlot(slot);
      if (card === void 0) return messagePage("Connecting to the engine\u2026");
      if (!card.widget) return messagePage("Not built yet. The slot is held so the numbers never shift.");
      return framePage(`${SERVER}/widget/${card.widget}?embed=1`);
    });
    this.slot = slot;
    this.panel = panel;
    panel.onDidDispose(() => windows.delete(slot));
    windows.set(slot, this);
    this.attach(panel.webview);
  }
  render() {
    const card = cardBySlot(this.slot);
    if (card !== void 0) this.panel.title = titleOf(card);
    super.render();
  }
};
function openWindow(slot, preserveFocus, column) {
  const existing = windows.get(slot);
  if (existing !== void 0) {
    existing.panel.reveal(existing.panel.viewColumn, preserveFocus);
    return existing;
  }
  const card = cardBySlot(slot);
  const panel = vscode.window.createWebviewPanel(
    VIEW_TYPE(slot),
    card === void 0 ? `Card ${slot}` : titleOf(card),
    { viewColumn: column ?? vscode.ViewColumn.Active, preserveFocus: preserveFocus === true },
    { enableScripts: true, retainContextWhenHidden: true }
  );
  return new CardWindow(slot, panel);
}
async function showHelp(title, html, reveal) {
  await ensureCards();
  lastDetails = { title, html };
  if (reveal === true) await vscode.commands.executeCommand("$PRODUCT_ID$.details.focus");
  if (detailsView !== null) detailsView.help(title, html);
}
async function expandDetails() {
  await ensureCards();
  const card = detailsCard();
  if (card === void 0) return;
  if (lastDetails === null) {
    void vscode.window.showInformationMessage("$PRODUCT$: click something first \u2014 a snapshot needs a subject.");
    return;
  }
  const shot = lastDetails;
  const panel = vscode.window.createWebviewPanel("$PRODUCT_ID$.snapshot", `Details \xB7 ${shot.title}`, vscode.ViewColumn.Active, {
    enableScripts: true,
    retainContextWhenHidden: true
  });
  const surface = new Surface(() => framePage(`${SERVER}/widget/${card.widget}?embed=1&frozen=1`));
  snapshots.add(surface);
  panel.onDidDispose(() => snapshots.delete(surface));
  surface.attach(panel.webview, () => surface.help(shot.title, shot.html));
}
async function showFieldHelp(which) {
  if (which === "filter") {
    await showHelp(
      "the log filter",
      "<p>Substring match over an act's time, hand, kind, brief and refusal clause.</p><p>The log is a terminal, so filtering redraws it. Clear the box to see everything again.</p>",
      false
    );
    return;
  }
  await showHelp(
    "drop a note",
    "<p>A stray: an idea, a bug, a better way. Enter captures it with your hand stamped on it.</p><p>It joins the feed at once and a retro drains it later.</p>",
    false
  );
}
var SCALE_HELP = {
  autonomy: {
    title: "the autonomy scale",
    lead: "<p>The agent enters a step only when that step weighs no more than this. At 0 nothing moves without you.</p>"
  },
  shutdown: {
    title: "the shutdown row",
    lead: "<p>Two buttons, either or both. Block auto-sleep holds the machine awake. Shutdown at idle shuts the machine down once the walk is parked and nothing has happened for five minutes.</p>"
  },
  narration: {
    title: "the update cadence",
    lead: "<p>How often the agent owes a line about what it is doing. Whichever falls due first counts, minutes or calls. A volunteered update always pays, and always resets both.</p>"
  }
};
async function showScaleHelp(which, level) {
  if (levels === null) levels = await api("/api/levels");
  const list = (levels === null ? null : levels[which]) ?? [];
  const rows = list.map((l) => {
    const here = level !== void 0 && Number(l.value) === Number(level);
    return `<tr${here ? ' style="font-weight:600"' : ""}><td>${escapeHtml(l.abbr)} \xB7 ${escapeHtml(String(l.value))}</td><td>${escapeHtml(l.name)}</td></tr>`;
  }).join("");
  const h = SCALE_HELP[which] ?? SCALE_HELP.autonomy;
  await showHelp(h.title, `${h.lead}<table class="kv">${rows}</table>`, false);
}
var GROUP_STYLE = `
  body { margin: 0; padding: 4px 0; background: var(--vscode-sideBar-background); color: var(--vscode-foreground); font-family: var(--vscode-font-family); font-size: var(--vscode-font-size); }
  svg { width: 16px; height: 16px; fill: none; stroke: currentColor; stroke-width: 1.2; stroke-linecap: round; stroke-linejoin: round; flex: none; }
`;
var Strip = class {
  constructor() {
    this.view = null;
  }
  tools() {
    const list = [
      { cmd: "$PRODUCT_ID$.help", icon: ICON.help, label: "What this is", key: "ctrl+alt+/" },
      { cmd: "$PRODUCT_ID$.startAgent", icon: ICON.play, label: "Start the agent", key: "ctrl+alt+enter" }
    ];
    for (const c of cards) {
      if (!inStrip(c)) continue;
      list.push({ cmd: `$PRODUCT_ID$.openCard${c.n}`, icon: cardIcon(c), label: titleOf(c), key: `ctrl+alt+${c.n}` });
    }
    return list;
  }
  page() {
    const rows = this.tools().map(
      (t) => `<button class="tool" data-cmd="${escapeHtml(t.cmd)}" title="${escapeHtml(t.key === "" ? t.label : `${t.label} \u2014 ${t.key}`)}">
      ${t.icon}<span class="label">${escapeHtml(t.label)}</span><span class="key">${escapeHtml(t.key)}</span></button>`
    ).join("");
    return `<!DOCTYPE html><html><head><meta charset="utf-8"><style>${GROUP_STYLE}
  button.tool { width: 100%; display: flex; align-items: center; gap: 8px; padding: 4px 10px; background: none; border: 0; color: var(--vscode-foreground); cursor: pointer; text-align: left; font: inherit; height: 26px; }
  button.tool:hover { background: var(--vscode-list-hoverBackground); }
  button.tool:focus-visible { outline: 1px solid var(--vscode-focusBorder); outline-offset: -1px; }
  .label { flex: 1; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
  .key { color: var(--vscode-descriptionForeground); font-size: .9em; opacity: .8; }
</style></head><body>
<div class="strip">${rows}</div>
<script>
  const vsapi = acquireVsCodeApi();
  document.addEventListener("click", (ev) => {
    const b = ev.target.closest ? ev.target.closest(".tool") : null;
    if (b) vsapi.postMessage({ se: "run", cmd: b.dataset.cmd });
  });
</script></body></html>`;
  }
  resolveWebviewView(view) {
    this.view = view;
    view.webview.options = { enableScripts: true };
    view.onDidDispose(() => {
      this.view = null;
    });
    view.webview.onDidReceiveMessage((m) => {
      if (m && m.se === "run") void vscode.commands.executeCommand(m.cmd);
    });
    this.render();
  }
  render() {
    if (this.view !== null) this.view.webview.html = this.page();
  }
};
var Controls = class {
  constructor() {
    this.view = null;
  }
  page() {
    return `<!DOCTYPE html><html><head><meta charset="utf-8"><style>${GROUP_STYLE}
  .box { padding: 2px 10px 8px; }
  .row { display: flex; align-items: baseline; justify-content: space-between; margin-top: 8px; }
  .name { color: var(--vscode-descriptionForeground); text-transform: uppercase; letter-spacing: .07em; font-size: .85em; cursor: pointer; }
  .name:hover { color: var(--vscode-foreground); }
  .val { font-family: var(--vscode-editor-font-family); }
  /* THE ENGINE'S CLASSES, dressed in the HOST'S COLOURS. params.ts decides
     WHICH controls exist and what they are; this decides only how they look
     in VS Code, from the theme's own variables. */
  /* ONE ROW PER CONTROL, LABEL FIRST. params.ts emits the rows; this only
     sizes them, so a new control needs no edit here. */
  .threshold { display: flex; flex-direction: column; gap: 6px; }
  .rungbar { margin-top: 4px; }
  .param-row { display: flex; align-items: center; gap: 6px; }
  .param-label { flex: 0 0 6.2em; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; color: var(--vscode-descriptionForeground); text-transform: uppercase; letter-spacing: .07em; font-size: .8em; cursor: pointer; }
  .param-label:hover { color: var(--vscode-foreground); }
  .rungs { display: flex; gap: 4px; flex: 1 1 auto; }
  .rung { flex: 1 1 auto; padding: 3px 4px; font: inherit; font-size: .85em; cursor: pointer; background: var(--vscode-button-secondaryBackground); color: var(--vscode-button-secondaryForeground); border: 1px solid var(--vscode-panel-border); border-radius: 4px; }
  .rung:hover { background: var(--vscode-button-secondaryHoverBackground); }
  .rung.on { background: var(--vscode-button-background); color: var(--vscode-button-foreground); border-color: var(--vscode-focusBorder); }
  /* Ideation delegates the CREATION of work, so its rung is drawn as a
     hazard rather than as a setting. RED, not a bordered blue: it was
     wearing the host's ordinary button background with a warning outline,
     which reads as any other pressed button. */
  .rung.on.danger { background: var(--vscode-charts-red); color: var(--vscode-button-foreground); border-color: var(--vscode-charts-red); border-width: 2px; }
  /* THE HIDDEN RUNG. Red and pulsing, so an armed engine cannot be mistaken
     for a merely delegated one. */
  .rung.emergency, .rung.on.danger.emergency { background: var(--vscode-charts-red); border-color: var(--vscode-charts-red); color: var(--vscode-button-foreground); animation: se-emergency 1.1s ease-in-out infinite; }
  @keyframes se-emergency { 0%, 100% { opacity: 1; } 50% { opacity: .45; } }
  @media (prefers-reduced-motion: reduce) { .rung.emergency { animation: none; outline: 2px solid var(--vscode-charts-red); outline-offset: 1px; } }
  .rung.locked { opacity: .4; cursor: not-allowed; }
  /* A pressed toggle lights like a pressed rung \u2014 it is the same kind of
     switch, and it was drawing itself unlit whatever its state. */
  .rung.param-toggle.on { background: var(--vscode-button-background); color: var(--vscode-button-foreground); border-color: var(--vscode-focusBorder); }
  .cadence { width: 3.4em; font: inherit; font-size: .9em; padding: 2px 4px; text-align: right; background: var(--vscode-input-background); color: var(--vscode-input-foreground); border: 1px solid var(--vscode-input-border, transparent); }
  .cadence-unit { color: var(--vscode-descriptionForeground); font-size: .8em; margin-right: 6px; }
  .param-action { flex: 0 0 auto; margin-left: auto; }
  .param-choice { flex: 0 0 auto; font: inherit; font-size: .85em; padding: 2px 4px; background: var(--vscode-dropdown-background); color: var(--vscode-dropdown-foreground); border: 1px solid var(--vscode-dropdown-border, transparent); }
  .sep { height: 1px; background: var(--vscode-panel-border); margin: 10px 0 2px; }
  input[type=text] { flex: 1 1 auto; min-width: 0; box-sizing: border-box; padding: 3px 6px; background: var(--vscode-input-background); color: var(--vscode-input-foreground); border: 1px solid var(--vscode-input-border, transparent); font: inherit; }
  input[type=text]::placeholder { color: var(--vscode-input-placeholderForeground); }
  input[type=text]:focus { outline: 1px solid var(--vscode-focusBorder); outline-offset: -1px; }
</style></head><body>
<div class="box">
  <!-- THE ENGINE'S BAR LANDS HERE, WHOLE \u2014 every row, every label, the two
       line edits and the note's priority. The shutdown control is not in it:
       the owner struck it on 2026-08-01, and the spec is what draws.
       NOTHING IS WRITTEN HERE. A label written here is what put "Autonomy"
       on screen twice, and hand-written fields are how the struck sliders
       survived a whole expedition. -->
  <div id="bar"></div>
</div>
<script>
  const vsapi = acquireVsCodeApi();
  const $ = (id) => document.getElementById(id);
  // A FIELD BEING TYPED IN IS NEVER REWRITTEN BY THE POLL \u2014 but only a FIELD.
  // Guarding on focus alone froze the whole bar after every click, because the
  // button just pressed still held it, so the poll skipped the redraw and the
  // control sat unchanged until focus moved.
  const typing = () => {
    const a = document.activeElement;
    if (a === null || a === undefined) return false;
    return a.tagName === "INPUT" || a.tagName === "TEXTAREA" || a.tagName === "SELECT";
  };
  // THE BAR IS THE ENGINE'S, injected whole. Nothing here decides what a
  // control looks like \u2014 params.ts drew it from the panel spec, and this
  // webview only carries the clicks back. Two drawings of one bar is what
  // put the old sliders on screen for a whole expedition after they were
  // struck from the spec.
  //
  // A BAR BEING TOUCHED IS NOT REDRAWN. Replacing the markup under a
  // pointer swallows the click and resets a half-typed number.
  function applyBar(html) {
    const el = $("bar");
    if (el === null || typeof html !== "string" || html === "") return;
    if (typing() && el.contains(document.activeElement)) return;
    if (el.innerHTML === html) return;
    el.innerHTML = html;
    // THE CLICK OUTRANKS AN IN-FLIGHT POLL. A poll that started before the
    // POST landed carries the OLD position, and letting it win made the
    // button flip back and then forward again \u2014 which is the "sometimes fast,
    // sometimes three seconds" the reader was seeing. The painted position
    // is held until the engine's own html agrees with it.
    if (pendingLevel === null) return;
    const hidden = el.querySelector("#thr");
    if (hidden !== null && Number(hidden.value) === pendingLevel) pendingLevel = null;
    else paintRungs(pendingLevel);
  }

  // THE CLICK PAINTS ITSELF, THEN TELLS THE ENGINE. The round trip is a POST
  // plus a full re-render of the bar, and on this poll that is seconds. A
  // button that waits for it reads as broken, so the bank is repainted from
  // the click and the next poll only confirms what is already on screen.
  let pendingLevel = null;
  // The drumroll's memory outlives the bar, which is replaced wholesale on
  // every poll \u2014 anything stored on the button itself dies with it.
  let topPresses = 0;
  // WHEN THE RUN STARTED, not when the last click landed. The contract is
  // "five clicks in a second and a half", which is a property of the whole
  // run \u2014 a click-to-click timer would accept a slow, deliberate tapping
  // that never felt like a drumroll at all.
  let runStartedAt = 0;
  const DRUMROLL_MS = 1500;
  // WHEN IT ARMED. Nobody stops their hand exactly on the fifth click, and
  // the sixth would land on the armed button, release the rung and disarm
  // emergency instantly \u2014 the engine drops it the moment the autonomy falls
  // below the top. So the button goes deaf for a moment and lets the hand
  // finish.
  let armedAt = 0;
  const ARM_DEAF_MS = 2000;
  function paintRungs(level) {
    const el = $("bar");
    if (el === null) return;
    for (const b of el.querySelectorAll("button.rung[data-rung]")) {
      b.classList.toggle("on", Number(b.dataset.rung) <= level);
    }
    const hidden = el.querySelector("#thr");
    if (hidden !== null) hidden.value = String(level);
  }

  // ONE DELEGATED LISTENER, because the markup is replaced wholesale and
  // anything bound to an element inside it dies with the next poll.
  $("bar").addEventListener("click", (ev) => {
    const t = ev.target;
    if (!t || !t.closest) return;
    const rung = t.closest("button.rung[data-level]");
    if (rung !== null) {
      // THE HIDDEN RUNG, COUNTED BEFORE EVERY GUARD. The contract, in the
      // owner's words: five clicks on the top rung in a row go to emergency,
      // whatever rung the autonomy sits at, and it does not matter whether
      // the button is lit, dark or locked.
      //
      // Nothing may stand in front of this. The locked check below returns
      // silently, so from mechanical every click died there and no number of
      // presses could ever arm it.
      if (Number(rung.dataset.rung) >= 1) {
        const now = Date.now();
        // Deaf for two seconds after arming, so the tail of the drumroll
        // cannot undo it.
        if (now - armedAt < ARM_DEAF_MS) return;
        if (topPresses === 0 || now - runStartedAt > DRUMROLL_MS) {
          topPresses = 0;
          runStartedAt = now;
        }
        topPresses += 1;
        if (topPresses >= 5) {
          topPresses = 0;
          armedAt = now;
          // Emergency is refused below the top rung, so CLIMB first and arm
          // second. A refused arm is indistinguishable from a dead button.
          rung.classList.remove("locked");
          rung.classList.add("emergency");
          rung.textContent = "E";
          paintRungs(1);
          pendingLevel = 1;
          vsapi.postMessage({ se: "emergency" });
          return;
        }
      }
      if (rung.classList.contains("locked")) return;
      const level = Number(rung.dataset.level);
      pendingLevel = level;
      paintRungs(level);
      vsapi.postMessage({ se: "autonomy", value: level });
      // THE HELP FOLLOWS THE RUNG PRESSED, never where the walk lands.
      // Releasing the lowest rung lands on 0, and explaining "blocked" to
      // someone who just clicked the mechanical rung is the wrong mapping.
      vsapi.postMessage({ se: "scale-help", which: "autonomy", level: Number(rung.dataset.rung) });
      return;
    }
    // THE SHUTDOWN ROW. Independent on/off buttons, any combination lit at
    // once. The host had NO branch for these at all: the buttons rendered,
    // and a click did nothing whatever \u2014 no light, no behaviour, no post.
    const tog = t.closest(".param-toggle[data-toggle]");
    if (tog !== null) {
      const on = tog.getAttribute("aria-pressed") !== "true";
      // Paint first. The bar redraws on the next poll and waiting for that is
      // a second of a button that looks dead.
      tog.classList.toggle("on", on);
      tog.setAttribute("aria-pressed", on ? "true" : "false");
      vsapi.postMessage({ se: "power", key: tog.dataset.toggle, on });
      return;
    }
    const act = t.closest(".param-action[data-post]");
    if (act !== null) {
      // THE NOTE'S BUTTON CARRIES THE LINE. Every other action posts an empty
      // body; this one would drop a blank note without the field beside it.
      if (act.dataset.post === "/note") { captureNote(); return; }
      vsapi.postMessage({ se: "post", path: act.dataset.post });
      return;
    }
    if (t.closest(".thr-help") !== null) { vsapi.postMessage({ se: "scale-help", which: "autonomy" }); return; }
    if (t.closest(".nr-help") !== null) { vsapi.postMessage({ se: "scale-help", which: "narration" }); return; }
    // GENERIC ROW HELP: every labelled row explains itself on click. The
    // help text rides the label, so a new row needs no branch here.
    const rowLbl = t.closest(".param-label[data-help]");
    if (rowLbl !== null) vsapi.postMessage({ se: "row-help", label: rowLbl.textContent, text: rowLbl.dataset.help });
  });

  // THE LOG'S TWO LINE EDITS ARE PANEL PARAMETERS NOW, so they arrive inside
  // the bar and are reached the same delegated way as every other control.
  $("bar").addEventListener("input", (ev) => {
    const t = ev.target;
    if (!t || !t.closest || t.closest('.param-text[data-key="log_filter"]') === null) return;
    vsapi.postMessage({ se: "log-filter", text: t.value });
  });
  $("bar").addEventListener("focusin", (ev) => {
    const t = ev.target;
    if (!t || !t.closest || t.closest(".param-text") === null) return;
    if (t.dataset.key === "log_filter") vsapi.postMessage({ se: "field-help", which: "filter" });
    else if (t.dataset.key === "note_body") vsapi.postMessage({ se: "field-help", which: "note" });
  });
  // THE NOTE CARRIES ITS MoSCoW. The choice sits on the same row, so the
  // weight is picked where the stray is written rather than at a retro.
  function captureNote() {
    const field = $("bar").querySelector('.param-text[data-key="note_body"]');
    if (field === null || field.value.trim() === "") return;
    const pri = $("bar").querySelector('.param-choice[data-key="note_priority"]');
    vsapi.postMessage({ se: "note", text: field.value, priority: pri === null ? "could" : pri.value });
    field.value = "";
  }
  $("bar").addEventListener("keydown", (ev) => {
    const t = ev.target;
    if (!t || !t.closest || t.closest('.param-text[data-key="note_body"]') === null) return;
    if (ev.key !== "Enter") return;
    captureNote();
  });

  // THE CADENCE GOES OVER AS A PAIR, because POST /narration reads
  // {minutes, calls} and a missing half arrives as NaN.
  $("bar").addEventListener("change", (ev) => {
    if (!ev.target || !ev.target.closest || ev.target.closest(".cadence") === null) return;
    const box = (key) => $("bar").querySelector('.cadence[data-key="' + key + '"]');
    const min = box("narration_minutes"), calls = box("narration_calls");
    vsapi.postMessage({ se: "narration", minutes: min === null ? 0 : Number(min.value), calls: calls === null ? 0 : Number(calls.value) });
  });

  window.addEventListener("message", (ev) => {
    const d = ev.data;
    if (!d || d.se !== "state") return;
    applyBar(d.bar);
  });
</script></body></html>`;
  }
  send() {
    if (this.view === null) return;
    void this.view.webview.postMessage({ se: "state", packet, levels, bar });
  }
  resolveWebviewView(view) {
    this.view = view;
    view.webview.options = { enableScripts: true };
    view.onDidDispose(() => {
      this.view = null;
    });
    view.webview.onDidReceiveMessage(async (m) => {
      if (!m) return;
      if (m.se === "log-filter") {
        logFilter = String(m.text ?? "");
        redrawLog();
        return;
      }
      if (m.se === "note") {
        await post("/note", { text: m.text, priority: m.priority });
        await pollLog();
        return;
      }
      if (await handleBarHelp(m)) return;
      if (m.se === "autonomy") await post("/autonomy", { value: m.value });
      else if (m.se === "emergency") {
        await post("/autonomy", { value: 1 });
        await post("/emergency", { on: true });
      } else if (m.se === "power") await post("/power", { key: m.key, on: m.on });
      else if (m.se === "narration") await post("/narration", { minutes: m.minutes, calls: m.calls });
      else if (m.se === "post" && typeof m.path === "string" && m.path.startsWith("/")) await post(m.path, {});
      await pollWalk();
    });
    this.render();
    startPolling();
  }
  render() {
    if (this.view !== null) {
      this.view.webview.html = this.page();
      this.send();
    }
  }
};
var REF_RE = /\[🔗\]/g;
var LINK = "[\u{1F517}]";
var PLAIN = (s) => s.replace(/\[[0-9;]*m/g, "").trimEnd();
var logRefs = /* @__PURE__ */ new Map();
var DIM = (s) => `\x1B[2m${s}\x1B[0m`;
var KIND_COLOUR = { call: "34", update: "35", note: "33", aq: "36" };
var paint = (code, s) => code === void 0 ? s : `\x1B[${code}m${s}\x1B[0m`;
function logRow(r) {
  const ts = String(r.ts ?? "");
  const when = r.pending === true ? ts.slice(5, 10) : ts.slice(11, 19);
  const src = String(r.src ?? "");
  const kind = String(r.type ?? "");
  let brief = String(r.brief ?? "");
  if (brief.toLowerCase().startsWith(`${kind.toLowerCase()} `)) brief = brief.slice(kind.length + 1);
  const ok = r.ok === false ? "\x1B[31m\u2717\x1B[0m" : "\x1B[32m\u2713\x1B[0m";
  const clause = r.ok === false && r.clause ? ` ${String(r.clause)}` : "";
  const kindCol = paint(KIND_COLOUR[kind], kind.padEnd(6).slice(0, 6));
  const srcCol = src === "human" ? paint("97", src.padEnd(5)) : DIM(src.padEnd(5));
  return `${LINK} ${DIM(when)} ${srcCol} ${kindCol} ${brief}${clause} ${ok}`;
}
function matchesFilter(r) {
  const f = logFilter.trim().toLowerCase();
  return f === "" || `${r.ts} ${r.src} ${r.type} ${r.brief} ${r.clause ?? ""}`.toLowerCase().includes(f);
}
function appendLog() {
  if (logEmitter === null) return;
  const out = [];
  for (const r of logRows) {
    const ref = String(r.ref ?? "");
    if (ref === "" || logSeen.has(ref)) continue;
    logSeen.add(ref);
    if (!matchesFilter(r)) continue;
    const row = logRow(r);
    logRefs.set(PLAIN(row), ref);
    out.push(row);
  }
  if (out.length > 0) logEmitter.fire(`${out.join("\r\n")}\r
`);
}
function redrawLog() {
  if (logEmitter === null) return;
  logSeen.clear();
  logRefs.clear();
  const out = [];
  for (const r of logRows) {
    const ref = String(r.ref ?? "");
    if (ref !== "") logSeen.add(ref);
    if (!matchesFilter(r)) continue;
    const row = logRow(r);
    logRefs.set(PLAIN(row), ref);
    out.push(row);
  }
  logEmitter.fire(`\x1B[2J\x1B[3J\x1B[H${out.length === 0 ? DIM("no acts match") : out.join("\r\n")}\r
`);
}
async function pollLog() {
  const body = await api("/api/log");
  if (body === null || !Array.isArray(body.rows)) return;
  logRows = body.rows;
  appendLog();
}
function makeLogTerminal(parent) {
  const emitter = new vscode.EventEmitter();
  logEmitter = emitter;
  const opts = {
    name: "$PRODUCT$ log",
    pty: {
      onDidWrite: emitter.event,
      open: () => {
        logSeen.clear();
        void api("/api/log").then((b) => {
          if (b !== null && Array.isArray(b.rows)) logRows = b.rows;
          redrawLog();
        });
      },
      close: () => {
        logEmitter = null;
        logTerm = null;
      },
      handleInput: () => {
      }
    }
  };
  const anchor = parent ?? vscode.window.activeTerminal ?? vscode.window.terminals.find((t) => t !== logTerm) ?? null;
  logAnchored = anchor !== null && anchor !== void 0;
  if (logAnchored) opts.location = { parentTerminal: anchor };
  trace(`log terminal: anchor=${logAnchored ? anchor.name : "none"}`);
  logTerm = vscode.window.createTerminal(opts);
  return logTerm;
}
async function showLog(rebuild) {
  if (!await ensureServer()) return;
  if (rebuild === true && logTerm !== null) {
    logTerm.dispose();
    logTerm = null;
    logEmitter = null;
  }
  if (logTerm === null) makeLogTerminal(agentTerm);
  logTerm.show(true);
  await pollLog();
}
async function showLogRef(ref) {
  trace(`showLogRef ${ref} detailsView=${detailsView === null ? "null" : "ready"}`);
  await vscode.commands.executeCommand("$PRODUCT_ID$.details.focus");
  if (detailsView !== null) detailsView.post({ se: "logref", ref });
}
function psq(text) {
  return `'${String(text).replace(/'/g, "''")}'`;
}
function parseExcludedToolsFromCage(cage) {
  const args = Array.isArray(cage?.exclude_args) ? cage.exclude_args : [];
  const i = args.indexOf("--excluded-tools");
  if (i < 0) return [];
  const out = [];
  for (let n = i + 1; n < args.length; n++) {
    const a = String(args[n] ?? "").trim();
    if (a === "" || a.startsWith("--")) break;
    out.push(a);
  }
  return out;
}
async function openCopilotInChat(kickoff, cage) {
  const all = await vscode.commands.getCommands(true);
  if (!all.includes("workbench.action.chat.open")) return false;
  const toolsExclude = parseExcludedToolsFromCage(cage);
  try {
    await vscode.commands.executeCommand("workbench.action.chat.open", {
      mode: "agent",
      query: kickoff,
      isPartialQuery: false,
      toolsExclude
    });
    return true;
  } catch {
    return false;
  }
}
var CLAUDE_SIDEBAR_COMMAND = "claude-vscode.sidebar.open";
var CLAUDE_EDITOR_COMMAND = "claude-vscode.editor.open";
var CLAUDE_FOCUS_COMMAND = "claude-vscode.focus";
async function confirmLaneIsReachable() {
  const reload = "Reload Window";
  const anyway = "Start Anyway";
  const pick = await vscode.window.showWarningMessage(
    "$PRODUCT$: the engine only came up just now, so an agent already loaded in this window cannot see the se tools.",
    {
      modal: true,
      detail: "Reload the window and the engine starts first, so the agent finds the lane. Start anyway only if no agent has loaded yet."
    },
    reload,
    anyway
  );
  if (pick === reload) {
    void vscode.commands.executeCommand("workbench.action.reloadWindow");
    return false;
  }
  return pick === anyway;
}
async function openClaudeInSideBar(kickoff) {
  const all = await vscode.commands.getCommands(true);
  try {
    if (all.includes(CLAUDE_SIDEBAR_COMMAND)) {
      await vscode.commands.executeCommand(CLAUDE_SIDEBAR_COMMAND);
      await sendKickoffToClaude(kickoff);
      trace("claude opened in the side bar; kickoff pasted and sent");
      return true;
    }
    if (all.includes(CLAUDE_EDITOR_COMMAND)) {
      await vscode.commands.executeCommand(CLAUDE_EDITOR_COMMAND, void 0, kickoff);
      await vscode.commands.executeCommand("workbench.action.focusActiveEditorGroup");
      setTimeout(() => void sendEnterOnly(), 600);
      trace("claude opened in one editor tab with the kickoff; Enter follows");
      return true;
    }
    trace("no Claude Code command is registered \u2014 the extension is absent or inactive");
    return false;
  } catch (err) {
    trace(`opening claude failed: ${String(err)}`);
    return false;
  }
}
async function sendKickoffToClaude(kickoff) {
  const previous = await vscode.env.clipboard.readText();
  await vscode.env.clipboard.writeText(kickoff);
  const focus = async () => {
    try {
      await vscode.commands.executeCommand(CLAUDE_FOCUS_COMMAND);
    } catch (err) {
      trace(`focus attempt failed (the view may still be mounting): ${String(err)}`);
    }
  };
  await focus();
  setTimeout(() => void focus(), 400);
  setTimeout(() => void focus(), 800);
  setTimeout(() => {
    void focus();
    void sendPasteAndEnter();
  }, 1100);
  setTimeout(() => void vscode.env.clipboard.writeText(previous), 6e3);
}
async function sendPasteAndEnter() {
  if (!keys.available()) {
    trace("no key sender on this platform \u2014 the kickoff is on the clipboard, paste it and press Enter");
    return;
  }
  if (!vscode.window.state.focused) {
    trace("window not focused \u2014 keys withheld; the kickoff is on the clipboard");
    return;
  }
  if (keys.paste() === 0) {
    trace("paste could not be sent");
    return;
  }
  await new Promise((r) => setTimeout(r, 250));
  let sent = 0;
  for (let i = 0; i < 10; i++) {
    if (!vscode.window.state.focused) {
      trace(`focus left mid-send after ${sent} Enter(s) \u2014 the rest are withheld`);
      return;
    }
    if (keys.enter() > 0) sent++;
    await new Promise((r) => setTimeout(r, 150));
  }
  trace(sent > 0 ? `${sent} Enter(s) went \u2014 if the kickoff still sits unsent, press it yourself` : "Enter never went \u2014 press it yourself");
}
async function sendEnterOnly() {
  if (!keys.available()) {
    trace("no key sender on this platform \u2014 the kickoff is in the box, press Enter");
    return;
  }
  let sent = 0;
  for (let i = 0; i < 10; i++) {
    if (vscode.window.state.focused && keys.enter() > 0) sent++;
    await new Promise((r) => setTimeout(r, 150));
  }
  trace(sent > 0 ? `${sent} Enter(s) went \u2014 if the kickoff still sits unsent, press it yourself` : "Enter never went \u2014 press it yourself");
}
function sessionHeader(now) {
  const d = now ?? /* @__PURE__ */ new Date();
  const p = (n) => String(n).padStart(2, "0");
  return `Session ${d.getFullYear()}-${p(d.getMonth() + 1)}-${p(d.getDate())}T${p(d.getHours())}:${p(d.getMinutes())}`;
}
function agentLaunch(root) {
  const cageDir = path.join(root, "project", "_cage");
  const kickoff = `${sessionHeader()}

${readFileSync(path.join(cageDir, "kickoff.txt"), "utf8").trim()}`;
  const has = (cmd) => spawnSync(cmd, ["--version"], { encoding: "utf8", shell: true }).status === 0;
  if (has("claude")) return { host: "claude", kickoff, command: `claude ${psq(kickoff)}` };
  if (has("copilot")) {
    const cage = JSON.parse(readFileSync(path.join(cageDir, "copilot-cage.json"), "utf8"));
    const args = [].concat(cage.mcp_args, cage.exclude_args, cage.allow_args, cage.deny_args, cage.extra_args);
    return {
      host: "copilot",
      kickoff,
      cage,
      command: `copilot ${args.map((a) => psq(a)).join(" ")} -i ${psq(kickoff)}`
    };
  }
  return null;
}
async function startAgent() {
  if (agentStarting) {
    void vscode.window.showInformationMessage(
      "$PRODUCT$: agent is already starting \u2014 check '$PRODUCT$ agent' and '$PRODUCT$ log' terminals."
    );
    return;
  }
  agentStarting = true;
  try {
    const ok = await vscode.window.withProgress(
      {
        location: vscode.ProgressLocation.Notification,
        title: "$PRODUCT$: starting agent \u2014 check the terminals",
        cancellable: false
      },
      async (progress) => {
        progress.report({ message: "Preparing engine and launch command..." });
        const root = projectRoot();
        if (root === null || !await ensureServer()) return false;
        if (serverJustStarted && !await confirmLaneIsReachable()) return false;
        await ensureCards();
        const command = agentLaunch(root);
        if (command === null) {
          void vscode.window.showErrorMessage("$PRODUCT$: no agent CLI found \u2014 install Claude Code (or Copilot CLI), then retry.");
          return false;
        }
        progress.report({ message: "Opening terminals and launching agent..." });
        if (command.host === "claude") {
          progress.report({ message: "Opening Claude and handing it the kickoff..." });
          if (await openClaudeInSideBar(command.kickoff)) {
            agentTerm = null;
            await showLog(false);
            return true;
          }
          progress.report({ message: "Claude Code extension unavailable, falling back to terminal launch..." });
        }
        if (command.host === "copilot") {
          progress.report({ message: "Opening Copilot Chat and sending kickoff..." });
          const launchedInChat = await openCopilotInChat(command.kickoff, command.cage);
          if (launchedInChat) {
            agentTerm = null;
            await showLog(false);
            return true;
          }
          progress.report({ message: "Chat launch unavailable, falling back to terminal launch..." });
        }
        agentTerm = vscode.window.createTerminal({
          name: "$PRODUCT$ agent",
          cwd: path.join(root, "project")
        });
        agentTerm.sendText(command.command, true);
        await showLog(true);
        agentTerm.show(true);
        return true;
      }
    );
    if (ok) {
      void vscode.window.setStatusBarMessage(
        "$PRODUCT$: agent started \u2014 Claude runs the kickoff itself; Copilot runs in Chat; logs are in '$PRODUCT$ log'.",
        5e3
      );
    }
  } finally {
    agentStarting = false;
  }
}
async function openCard(n) {
  if (!await ensureServer()) return;
  await ensureCards();
  const card = cardBySlot(n);
  if (!shown(card)) {
    void vscode.window.showInformationMessage(`$PRODUCT$: project/views/cards.md declares no card ${n}.`);
    return;
  }
  await showHelp(titleOf(card), cardHelp(card), false);
  if (card.widget === "details") {
    await vscode.commands.executeCommand("$PRODUCT_ID$.details.focus");
    return;
  }
  if (card.widget === "log") {
    await showLog(false);
    return;
  }
  openWindow(n, false);
}
function showAttach() {
  const root = projectRoot();
  if (root === null) return;
  const doc = vscode.Uri.file(path.join(root, "project", "deliverable", "vscode", "ATTACH.md"));
  void vscode.commands.executeCommand("markdown.showPreview", doc);
}
function withHelp(cmd, run) {
  return async (...args) => {
    const h = HELP[cmd];
    if (h !== void 0) await showHelp(h.title, h.html, false);
    await run(...args);
  };
}
function activate(context) {
  try {
    BUILD = new Date(statSync(__filename).mtime).toISOString().slice(0, 16).replace("T", " ");
  } catch {
  }
  trace(`ACTIVATE build=${BUILD}`);
  output = vscode.window.createOutputChannel("$PRODUCT$ Engine");
  strip = new Strip();
  controls = new Controls();
  detailsView = new CardView("details");
  const keepAlive = { webviewOptions: { retainContextWhenHidden: true } };
  context.subscriptions.push(
    output,
    vscode.window.registerWebviewViewProvider("$PRODUCT_ID$.tools", strip, keepAlive),
    vscode.window.registerWebviewViewProvider("$PRODUCT_ID$.controls", controls, keepAlive),
    vscode.window.registerWebviewViewProvider("$PRODUCT_ID$.details", detailsView, keepAlive),
    // A REFERENCE IN THE LOG TERMINAL IS A LINK. This is what buys back the
    // clicking a webview log had, without a second log to keep in step.
    vscode.window.registerTerminalLinkProvider({
      provideTerminalLinks: (ctx) => {
        const out = [];
        REF_RE.lastIndex = 0;
        let m = REF_RE.exec(ctx.line);
        while (m !== null) {
          const ref = logRefs.get(PLAIN(ctx.line));
          if (ref !== void 0 && ref !== "")
            out.push({ startIndex: m.index, length: m[0].length, tooltip: "show this act in Details", ref });
          m = REF_RE.exec(ctx.line);
        }
        trace(`links asked line=${JSON.stringify(ctx.line.slice(0, 50))} gave=${out.length} known=${logRefs.size}`);
        return out;
      },
      handleTerminalLink: (link) => {
        trace(`link clicked ref=${String(link.ref)}`);
        void showLogRef(link.ref);
      }
    }),
    // A LOG THAT HAD NOTHING TO SIT BESIDE gets re-split the moment a terminal
    // appears. Otherwise it stays in a group of its own forever, which is what
    // happens whenever the agent was started outside this window.
    vscode.window.onDidOpenTerminal((t) => {
      if (logTerm === null || t === logTerm || logAnchored) return;
      trace(`log re-splitting beside ${t.name}`);
      void showLog(true);
    }),
    vscode.window.onDidCloseTerminal((t) => {
      if (t === agentTerm) agentTerm = null;
      if (t === logTerm) {
        logTerm = null;
        logEmitter = null;
      }
    }),
    vscode.commands.registerCommand("$PRODUCT_ID$.help", () => void showHelp("$PRODUCT$", systemHelp(), true)),
    vscode.commands.registerCommand("$PRODUCT_ID$.startAgent", withHelp("$PRODUCT_ID$.startAgent", startAgent)),
    vscode.commands.registerCommand("$PRODUCT_ID$.howToAttach", showAttach),
    vscode.commands.registerCommand("$PRODUCT_ID$.expandDetails", () => void expandDetails()),
    vscode.window.onDidChangeActiveColorTheme(() => {
      strip.render();
      controls.render();
      detailsView.theme();
      for (const s of snapshots) s.theme();
      for (const w of windows.values()) w.theme();
    }),
    {
      dispose: () => {
        if (poller !== null) clearInterval(poller);
      }
    }
  );
  for (let n = 1; n <= SLOTS; n++) {
    context.subscriptions.push(
      vscode.commands.registerCommand(`$PRODUCT_ID$.openCard${n}`, () => void openCard(n)),
      // WITHOUT THIS THE LAYOUT IS A LIE. VS Code drops every webview editor
      // on a window reload unless its type can be deserialized — so the
      // windows a person arranged would come back empty, and the promise
      // that VS Code remembers their layout would hold for the positions
      // and not for the contents.
      vscode.window.registerWebviewPanelSerializer(VIEW_TYPE(n), {
        deserializeWebviewPanel: async (panel) => {
          new CardWindow(n, panel);
        }
      })
    );
  }
  void ensureServer().then(async (ok) => {
    if (!ok) return;
    await refreshCards();
    startPolling();
  });
}
function killTree(proc) {
  if (proc === null || proc === void 0) return;
  const pid = proc.pid;
  proc.kill();
  if (process.platform === "win32" && pid !== void 0) {
    try {
      spawnSync("taskkill", ["/PID", String(pid), "/T", "/F"], { windowsHide: true });
    } catch {
    }
  }
}
function deactivate() {
  disposed = true;
  if (poller !== null) clearInterval(poller);
  killTree(child);
}
module.exports = { activate, deactivate };
